### ISSUE TITLE
authentication issue woith qbitTorrent 3.2.0?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bogenpirat/remote-torrent-adder#145]
```
What version of Chrome are you using? On what operating system?
Version 42.0.2311.135 m (64-bit), win7 64bit
What client (version?) are you connecting to? Are you using SSL?
qbitTorrent ,3.2.0
What steps will reproduce the problem?
1.try to add torrent to password protect qbittorrent client (no ssl)
2.failed


What is the expected output? What do you see instead?
expect output - torrent added succefully
actual output - http error 403

note - if qbitotrrent is configured to  skip authentication to localhost 
requests - torrent is added successfully
```

Original issue reported on code.google.com by `gus...@gmail.com` on 12 May 2015 at 4:10

**Comment by Misiek304** [comment]
Any update about this situation?

**Comment by bogenpirat** [comment]
it's on the agenda, but i can't give you a timeline.

**Comment by jhoward15** [comment]
Does the above update ([Add support for qbittorrent webui v3.2+ #158](https://github.com/bogenpirat/remote-torrent-adder/issues/158)) fix this now? If so, how do I get an updated copy of the extension with the fix?

**Comment by PaysPlat** [comment]
Hi, Can you release updated version with support of qbitorrent v3.2+.
It works well but Chrome deactivates it when relaunch because it is not on Web store.

Thank you and great work.

**Comment by bogenpirat** [comment]
i've kept you guys hanging for too long, pushed the update out just now. thanks again to @savingprivatebryan for the clean PR.

**Comment by Misiek304** [comment]
It was only one year.
Could have been worse...
