### ISSUE TITLE
Server didn't accept data: 200: ERROR Message

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bogenpirat/remote-torrent-adder#150]
```
What version of Chrome are you using? On what operating system?

v43

What client (version?) are you connecting to? Are you using SSL?

rtorrent: 0.9.4
rutorrent: 0.13.4
nginx for the web server

Yes, using SSL

What steps will reproduce the problem?

Settings: http://i.imgur.com/V5Nv6zZ.png

Adding any magnet link causes the error

What is the expected output? What do you see instead?

torrent gets added

-------
error.log states:
[22.07.15 09:39:14] <?xml version="1.0" 
encoding="UTF-8"?><methodCall><methodName>load_start</methodName><params>^M
<param><value><string>magnet:?somethingsomething</string></value></param>^M
</params></methodCall>
[22.07.15 09:39:14] Status: 200 OK^M
Content-Type: text/xml^M
Content-Length: 311^M
^M
<?xml version="1.0" encoding="UTF-8"?>^M
<methodResponse>^M
<fault>^M
<value><struct>^M
<member><name>faultCode</name>^M
<value><i4>-506</i4></value></member>^M
<member><name>faultString</name>^M
<value><string>Method 'load_start' not defined</string></value></member>^M
</struct></value>^M
</fault>^M
</methodResponse>^M
```

Original issue reported on code.google.com by `eper...@gmail.com` on 22 Jul 2015 at 1:50

**Comment by didyouexpectthat** [comment]
This add-on is no longer usable to me because of this error.

**Comment by didyouexpectthat** [comment]
#142 is a similar bug.

**Comment by pax0707** [comment]
Chrome 47, Windows 10, utorrent 2.2.1

Was working fine till few days ago.

**Comment by tomballgithub** [comment]
I verified tonight using Chrome Portable that it works up through Chrome 46 standard but fails with Chrome 47 (beta)

**Comment by didyouexpectthat** [comment]
And still broken in Chrome 48 for .torrent files.

**Comment by jzell** [comment]
maybe this'll help. can someone check whether that fixes the issue?

instructions: https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code
zip file: https://github.com/bogenpirat/remote-torrent-adder/archive/master.zip

**Comment by bogenpirat** [comment]
maybe this'll help. can someone check whether that fixes the issue?

instructions: https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code
zip file: https://github.com/bogenpirat/remote-torrent-adder/archive/master.zip

**Comment by pax0707** [comment]
Works in Chrome 47

**Comment by didyouexpectthat** [comment]
That worked for me in Chrome 48. Thank you.

**Comment by bogenpirat** [comment]
cheers, gonna push  1.2.6 in a few minutes. should arrive within the hour, you can kill the experimental versions.
