### ISSUE TITLE
Feature request: Support for Synology's Download Station

### ISSUE THREAD

**Issue by dolphinkite** [bogenpirat/remote-torrent-adder#159]
Synology NAS includes a BitTorrent client called Download Station that uses Transmission (at the moment 2.84) behind the scene.

At the moment, I am using remote-torrent-adder for my ruTorrent and uTorrent clients, but must use this (https://www.download-station-extension.com/) extension for managing my torrents on the NAS. That extension offers more possibility (such as viewing current status of all torrents, stop and start them, current transfer rates, etc.). But the reality is that I only want the extension to be able to add torrents, which remote-torrent-adder does very well. 

I which you supported Synology's Download Station too so I (and others) can consolidate everything in one extension.

Thanks

**Comment by bogenpirat** [comment]
if it uses transmission, shouldn't the transmission support in the extension already provide support for your nas's client?

**Comment by dolphinkite** [comment]
I had tried to add it as a Transmission server (but it says Transmission WebUI and I don't think that my NAS is running the webui from Transmission..?) and it didn't work.

The error message I get is: "The server didn't accept data" and there is more data - Can I have access to a log file to paste the complete response here?

**Comment by bogenpirat** [comment]
okay, so it seems like synology don't offer an api and i don't have one to try stuff out on.

RTA doesn't log anything. that would require understanding responses that change all the time for a dozens clients. i found some code online, but it wouldn't work with RTA. is there a method in the web ui of straight up uploading a torrent file? if so, support a general possibility.

**Comment by dolphinkite** [comment]
Yes, from the webui, I can either add a torrent through uploading a file, or pasting a URL to a .torrent file.


Download-station-extension (see above) does it as a chrome extension and Transdroid also is able to do it (in Transdroid, the options are separate to add a Synology server and to add a Transmission server).

Here is a link to Transdroid's souce code: https://github.com/erickok/transdroid. There, it seems a commit 3 years ago is about adding support for Synology (according to the comment) and inside, you see all the modifications he had to make . Specifically, there is a file called lib/src/org/transdroid/daemon/Synology/SynologyAdapter.java where the core code seems to be.

**Comment by jzell** [comment]
Yeah I saw that, but the only way of adding torrents implemented in their code is via url. RTA doesn't do that. We'd likely need to reverse engineer the file adding method which I can't do without a specimen to pay around with, or at the very least a request dump of some sort.

**Comment by bogenpirat** [comment]
Yeah I saw that, but the only way of adding torrents implemented in their code is via url. RTA doesn't do that. We'd likely need to reverse engineer the file adding method which I can't do without a specimen to pay around with, or at the very least a request dump of some sort.

**Comment by bogenpirat** [comment]
for future reference: [here](https://global.download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf) is an api document that describes all the necessary calls, including file upload.

**Comment by bogenpirat** [comment]
thanks to @dolphinkite i've made a lot of progress.

there is however an issue with magnet links for which i'll need someone to test an [experimental version](https://github.com/bogenpirat/remote-torrent-adder/archive/1fad2bafd228c8dd2f82563c51c57fc46c8a4015.zip) and use [these instructions](https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code) to try it out.

thanks.

**Comment by bogenpirat** [comment]
i'd have preferred to have someone test this, but since nobody seems to be interested, i've pushed it to the webstore for the public to test. let me know in a new issue if it's broken.

**Comment by marcolino7** [comment]
Hi,
I have a Synology NAS with DSM 6.1 and Download Station. I selected Synology WebUI but when I try to add torrent, i got no errors but i got no success and torrent is not added.

Can you help  me?

Marco
