### ISSUE TITLE
Irregular HTTP error 403

### ISSUE THREAD

**Issue by joelwyrick** [bogenpirat/remote-torrent-adder#162]
What version of Chrome are you using? On what operating system?
Chrome Version 48.0.2564.116 m - on Win10 x64 vmware session running on - Win8 x64 using NAT (share the hosts network)

What client (version?) are you connecting to? Are you using SSL?
qBittorrent v3.3.3, no ssl

What steps will reproduce the problem?
1.Client install, Web UI configuration
2. Remote Torrent Adder configuration (needless to say, same as client)
3. Trying to add a magnet link or opening a .torrent file

What is the expected output? What do you see instead?
Adding the torrent to the list. Instead I see this popup:
http://i.imgur.com/jszLIMS.png

**Comment by bogenpirat** [comment]
#158 contains the fix for this. i've been waiting for someone to confirm another feature in #159 that i'm waiting for someone to test before i'll release both in a new version.

**Comment by jhoward15** [comment]
Any chance we can get a new release with just the qbtorrent fix? That would be great.
