### ISSUE TITLE
Use WebExtensions to port to firefox

### ISSUE THREAD

**Issue by currowth** [bogenpirat/remote-torrent-adder#163]
Can you port this plugin to firefox using WebExtensions if it is possible?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by bogenpirat** [comment]
I don't have any interest in writing and supporting an extension for Firefox, so no, sorry.

If you manage to find someone to take that on, I'll be happy to support them with documentation on why I solve some things as terribly as i do though.
