### ISSUE TITLE
Show queue

### ISSUE THREAD

**Issue by Symbai** [bogenpirat/remote-torrent-adder#164]
If I have like 12 tabs in click in all of them on download, it is hard to see which tab was successful in adding torrent and which not.

I would like to have a popup window with a queue so I know it actually does uploading it to the seedbox and if a specific torrent is done or still uploading. The only notification after it has finished is not useful if you add more than one per time.

**Comment by bogenpirat** [comment]
i kinda don't think that's a common use case. the idea of the extension is to quickly click a link to add a torrent/magnet to a webui. if this process is prone to being slow AND failing, you should probably fix your server instead. i don't see a use for this outside of bad servers.
