### ISSUE TITLE
Irregular HTTP Error Code 401

### ISSUE THREAD

**Issue by MDS0LDI3R** [bogenpirat/remote-torrent-adder#165]
What version of Chrome are you using? On what operating system?
52.0.2743.82 m (64-bit) on  WIndows 10 Pro OS Build 10586.494.

What client (version?) are you connecting to? Are you using SSL?
ruTorrent 3.7 with SSL.

What steps will reproduce the problem?
1. Clicking on link with torrent.
2. Clicking "Add Torrent" on the in tab popup regarding directory/label.

What is the expected output? What do you see instead?
Expect to see green pop up instead I see a red pop up with:

> Failure
> Server responded with an irregular HTTP
> error code:
> 401: <!DOCTYPE HTML PUBLIC "-//IETF//DTD
> HTML 2.0//EN">
> <html> <head>...

Additional Information:
    I am currently using this extension on another computer(OS: OS X EL Capitan 10.11.6. Browser: Google Chrome 51.0.2704.103 (64-bit)) to connect to the same server with no problem. In the Remote Torrent Adder options for this server I have identical input for Name, Type Host, Port, SSL, Username, Relative path and Label/Directory interactivity. The password has been both copied and pasted from a text file and hand typed multiple times.

Does anyone have any suggestions on what to try to get this extension to work on this Windows machine?

**Comment by bogenpirat** [comment]
self-signed certificate per chance?

**Comment by nwgat** [comment]
i have had issues using ssl but i had to re-login to rutorrent to get remote torrent adder to work

ps: not this issue my issue gave no errors
