### ISSUE TITLE
Can't get extension

### ISSUE THREAD

**Issue by zartyblartfast** [bogenpirat/remote-torrent-adder#171]
Can't see how or where to get the remote-torrent-adder extension from the page... 

https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci   

I'm using a macbook OS X ... not sure if that has anything to do with it?

**Comment by bogenpirat** [comment]
Tried this?

https://www.google.de/url?sa=t&source=web&rct=j&url=https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci%3Fhl%3Den&ved=0ahUKEwjHm7zYyubOAhUGuhQKHfaWBDkQFggbMAA&usg=AFQjCNGpWfsEgW9qCQQy0l9aC5TYq0EGZA&sig2=08SyIXKGvn3vAZOttzbIDQ

**Comment by zartyblartfast** [comment]
Yes, that's the page I saw before.  Maybe I'm being stupid but I can not see anywhere on that page where to download the extension.

**Comment by bogenpirat** [comment]
there's a button in the top right of the page that for me says "added to chrome", but for you should be blue and read "add to chrome", cf [screenshot](https://cloud.githubusercontent.com/assets/1835496/18055890/faa0a4ce-6e09-11e6-9d58-04ebe76011d3.png).
