### ISSUE TITLE
Server didn't accept data: 200 Error has resurfaced.

### ISSUE THREAD

**Issue by S-Prime** [bogenpirat/remote-torrent-adder#172]
After version 1.2.7 of Remote Torrent Adder installed, I have started getting the Server didn't accept data: 200 error. I am using rutorrent and the latest version of Chrome (Version 53.0.2785.89 m). I can copy the URL for the torrent and paste it manually into rutorrent and it accepts it, fails using Remote Torrent Adder. I don't remember the exact date that the issue started but it was about 2 weeks ago, which would coincide  with version 1.2.7.

**Comment by bogenpirat** [comment]
the ruTorrent code hasn't been touched since January 2015 (1.2.5), so 1.2.7 shouldn't be the cause of this.

mind taking a screenshot of the error message? do you have access to ruTorrent's error.log?

**Comment by S-Prime** [comment]
How do you access the error logs?

![error 200](https://cloud.githubusercontent.com/assets/21955617/18209505/ffd0c3de-7101-11e6-8364-01fd34582c0f.JPG)

**Comment by S-Prime** [comment]
ruTorrent v3.7 and I believe that you are correct that the problem is in ruTorrent. I have tried out on multiple computers and get the same results. Also, I am using Cheapseedbox and following their guide for using Remote Torrent Adder.

**Comment by S-Prime** [comment]
I finally got it to work, by using the url for the rutorrent site without including https://, instead of using the ip address for the host in Remote Torrent Adder.

**Comment by abonawaf71** [comment]
All you have to do is  change **Type Host** from your seedbox ip to "vertigo.myseedbox.site"

<img width="285" alt="screenshot 2016-09-07 19 44 06" src="https://cloud.githubusercontent.com/assets/22058042/18320673/854549b0-7533-11e6-85ec-db69b1d95996.png">
