### ISSUE TITLE
Export/Import settings option?

### ISSUE THREAD

**Issue by tsimmons** [bogenpirat/remote-torrent-adder#173]
This is probably an enhancement request but it would be nice if there were an option to export/import all options. I had a Chrome profile meltdown and had to recreate the settings from scratch.

**Comment by bogenpirat** [comment]
[this](https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings) should do the trick, no?

**Comment by tsimmons** [comment]
Sheesh; Perfect, +1

Thanks!
