### ISSUE TITLE
RTA not catching links

### ISSUE THREAD

**Issue by dreamspy** [bogenpirat/remote-torrent-adder#177]
Hi

I'm using RTA to catch links on a torrent site called torrentech.org. It fails to catch the links.

It might be related to the fact that the links look like this:

www.torrentech.org/index.php?act=attach&type=post&id=240489

ie. not direct links to the torrents.

Clicking this link opens up a new window which triggers a download of the torrent file. 

Note that I've ticked "new window" in RTA options.

reg
Frímann

**Comment by RainerZufahl** [comment]
Try opening the Options, then go to the "Link Catching" Tab and click on the highlighted button:
![image](https://user-images.githubusercontent.com/18621898/34826188-e143a5d4-f6d5-11e7-8126-c3b566ad051e.png)

Now in the new line that has appeared in the text field, paste the following line:

`torrentech\.org/index\.php\?act=attach&type=post&id=\d+`

I **think** this should work, but please come back to this thread if it doesn't and i'll try to fix it.
