### ISSUE TITLE
rta_modal_open is not a function / Version 55.0.2883.75 (64-bit) / MAC

### ISSUE THREAD

**Issue by notiles** [bogenpirat/remote-torrent-adder#179]
I get this error when I try to add a Torrent, the plugin was working perfectly before, but I think that a new Chrome version have break the code.

Error in event handler for extension.onRequest: TypeError: rta_modal_open is not a function
    at showLabelDirChooser (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/content_rta.js:108:2)
    at chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/content_rta.js:69:3

**Comment by bogenpirat** [comment]
nope, probably not chrome, but me; i fixed another couple issues and did a release after minimal testing.

can you tell me what exactly fails? i assume you have the label/directory dialog enabled, does that display? when exactly does the error occur? do you have a specific site where it fails?

i tried it out on https://www.ubuntu.com/download/alternative-downloads both with the option off and on and it seems to work fine.

**Comment by notiles** [comment]
After a little debug session, It appear that  the links array was empty, so I edit the regexp for link catching and it work better now... I don't understand why it was running before without editing the regexp...

**Comment by bogenpirat** [comment]
so it happened on pages where there were no torrents? or what

**Comment by notiles** [comment]
It happened on pages with links to a torrent like yts.ag or t411 that I was using before

**Comment by notiles** [comment]
In content_rta.js the links array (line 44) was empty when I was browsing a page with torrents links, that's why I get an error. So I add explicit string to link catching options and now it work on those two website.

**Comment by bogenpirat** [comment]
if that array is empty (or any of the other checks fail), then there won't be any event listeners registered for any elements, which would need to happen for this error to occur. do you happen to remember your old regex?

**Comment by notiles** [comment]
Yes it's the default regex ([\]\[]|\b|\.)\.torrent\b([^\-]|$)~torrents\.php\?action=download~yts.ag/torrent~torrents/download

**Comment by jonikang** [comment]
seriously, i am having the exact same error when adding torrent using the right click menu.

**Comment by bogenpirat** [comment]
@notiles thanks, but even with those i can't reproduce the issue.

@jonikang rutorrent? label/dir selection dialog enabled/disabled? specific site? what's your filter set?

**Comment by jonikang** [comment]
@bogenpirat 

the dir selection dialog is enabled. and ALL the torrent sites are not working with the latest update of the extension. I tried it on Ubuntu site you posted as well, and i am getting exact same error as on the other torrent sites. 

It is the default filter set and i didn't make any changes to the extension setting apart from the server settings.

I am now rolling back the extension to 8d4eaa7 and it works fine for now with 8d4eaa7.

**Comment by bogenpirat** [comment]
@jonikang 

well yeah, the function in question is an addition from 1.2.8, so an older version wouldn't exhibit this behavior. can you do a backup of your settings like so: https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings#backup, then remove the extension from chrome, reinstall it and only enter your server's information, not changing any of the settings outside the webui tab, and see if that works? bonus if it does: restore your settings using this: https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings#restore and check whether it's now not working anymore.

if this ends up showing that your particular settings are "at fault" for making this fail, i'd like to take a look at (some anonymized version of) them. maybe then i can reproduce and fix the error.

**Comment by jonikang** [comment]
@bogenpirat 

nice. I manually reset the localstorage, and just change my server setting it seems to be working fine from there onwards.

**Comment by bogenpirat** [comment]
ok, great. mind having a quick look through the json'd settings you backed up, change your sensitive data into XXXes and paste it here? i'd like to reproduce the problem and release an update that doesn't require nuking the settings.

**Comment by jonikang** [comment]
There you go

`{
    "catchfromcontextmenu": "true",
    "catchfrompage": "false",
    "client": "ruTorrent WebUI",
    "dirlist": "[\"SW\",\"MV\",\"SER\",\"MP3\",\"JUNK\",\"XXX\",\"DOC\",\"\",\"SYNC\"]",
    "host": "X",
    "hostsecure": "true",
    "labellist": "[\"SW\",\"MV\",\"SER\",\"MP3\",\"JUNK\",\"XXX\",\"DOC\",\"\",\"SYNC\"]",
    "linkmatches": "([\\]\\[]|\\b)\\.torrent\\b([^\\-]|$)~torrents\\.php\\?action=download~http://www.hdzone.org/attachment.php?aid=",
    "linksfoundindicator": "true",
    "login": "X",
    "password": "X",
    "popupduration": "10000",
    "port": "443",
    "ruTorrentrelativepath": "/rutorrent",
    "rutorrentdirlabelask": "true",
    "servers": "[{\"name\":\"X\",\"client\":\"ruTorrent WebUI\",\"host\":\"X\",\"port\":\"443\",\"hostsecure\":true,\"login\":\"X\",\"password\":\"X\",\"ruTorrentrelativepath\":\"/\",\"rutorrentlabel\":\"\",\"rutorrentdirectory\":\"\",\"rutorrentdirlabelask\":true,\"rutorrentaddpaused\":false},{\"name\":\"Deluge\",\"client\":\"Deluge WebUI\",\"host\":\"10.0.0.15\",\"port\":\"8112\",\"hostsecure\":false,\"login\":\"\",\"password\":\"X\",\"delugerelativepath\":\"\"}]",
    "showpopups": "true"
}`

**Comment by jonikang** [comment]
oh wait. it still doesn't really work on certain site. I will debug the extension tonight since i have cloned the repo and let you know my finding.

**Comment by bogenpirat** [comment]
thanks a lot for the settings. i restored them to a test instance, but unfortunately that didn't give me any errors either. so there's still no luck reproducing this one.

**Comment by jonikang** [comment]
that's okay, i will do it from my end and let you know what i  found.

**Comment by jonikang** [comment]
@bogenpirat finally got some idea why this is happening.

Apparently, if the <a> doesn't contain .torrent (as specified in the Regex), it doesn't hook up the event listener thus and also it doesn't init the modal. 

For example, most of the PT doesn't have .torrent in the <a> , but something looks like this, 
`attachment.php?aid=3517109&k=d33cf2763545bbc10c8628bf30717d3a&t=1481018716&ck=374bad4f&sid=9b0dCHn%2FoHtXW7EQ7Hq%2F2SXA84SMpZ265OGMTcd97gcbHoY`

The new code doesn't cater for that, and I have to add in the whole bunch of Link catching regex in the setting page to be able to catch those links and bring up the extension dialog.

I guess the main issue here is, the exception should be more intuitive, instead of getting this sort of terrible, horrifying javascript's common error - TypeError: <insert_here> is not a function

**Comment by bogenpirat** [comment]
wait, so this only happens when you have link catching *disabled* and are trying to add via the context menu?

**Comment by bogenpirat** [comment]
alright, i'm able to reproduce this now. 9d6e5d4 is a fix, i'll be pushing this within the hour. do please comment in here if 1.2.8.1 ends up not fixing this entirely.

**Comment by jonikang** [comment]
Yeah. that fixed it. Thanks for looking into the problem.
