### ISSUE TITLE
Clicking on blank space on any webpage causes Uncaught TypeError: Cannot set property 'className' of null

### ISSUE THREAD

**Issue by rwong48** [bogenpirat/remote-torrent-adder#180]
Started seeing these come from chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/modal.js by simply clicking on blank space on any webpage.

```
Uncaught TypeError: Cannot set property 'className' of null
closeModal @ modal.js:21
clickHandler @ modal.js:27
```

Reproduced with a fresh browser profile. Chrome 54.0.2840.98 on macOS 10.12.1

**Comment by bogenpirat** [comment]
man, that shitty fix keeps making me shit the bed. 1.2.8.2 will be out in a bit.
