### ISSUE TITLE
Directories/labels are not saved anymore

### ISSUE THREAD

**Issue by ktdd** [bogenpirat/remote-torrent-adder#183]
Ever since the last update with Directory interactivity checked, directories don't get saved anymore and have to be typed out every time.

Same thing for labels.

ruTorrent webui.

**Comment by bogenpirat** [comment]
i assume this is your workflow:

1. open site with torrents
2. click link, get to see the dir/label selection
3. add torrent
4. click another link, go to 2

what clicking the "add" button does is storing the settings in the background, but not updating the dropdown boxes (it never did that). if you hit f5 to refresh and click a torrent link again, the (new and old) label/directory settings you used while on the previous load of the page should be present in the dropdown boxes.

if that's not the case, mind removing the extension and re-adding it?

**Comment by ktdd** [comment]
That's exactly what I'm doing, what I have been doing since forever after reinstalling and this time it fails to work on both of my computers. One running Chrome Beta and one running Chrome Stable.

Also tried removing the extension and re-adding it, doesn't help.

**Comment by ktdd** [comment]
I downloaded an older version from Github and added it through developer mode; labels and directories save now. Just the latest version is broken

**Comment by bogenpirat** [comment]
alright, i see what you mean. on a fresh installation it does indeed bug out. i'll have it fixed in a few minutes.

**Comment by bogenpirat** [comment]
alright, published the fixes with 1.2.8.4. let me know here if this doesn't fix it. thanks for the report.

**Comment by ktdd** [comment]
Thanks for the quick fix, seems to be working fine. Now to wait for Google to update it.

**Comment by ktdd** [comment]
Another bug appeared probably related to this. Latest _added_ directory is always the default now, before it was the latest _used_ directory.

**Comment by bogenpirat** [comment]
alright, mind trying this one out for me?
[remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/664127/remote-torrent-adder.git.zip)

**Comment by ktdd** [comment]
That was fast! Bug has been fixed.

**Comment by bogenpirat** [comment]
yeah, you've been keeping me from compiling my shopping list!

since this one isn't major, i'll try to fix #184 before i release this one.

**Comment by ktdd** [comment]
Oh man, I'm sorry I've been bothering you this close to christmas. It's only that this extension is the only one that's keeping me from going from Chrome to Firefox, I just can't live without it.

**Comment by bogenpirat** [comment]
that's funny, just the other day a guy complained to me that no addon like RTA existed for firefox.

**Comment by ktdd** [comment]
It's true, there are literally no decent torrent managing extensions for Firefox. There's one to manage ruTorrent but it hasn't been updated since 2012 and it spazzes out every once in a while.

I even tried converting RTA to a Firefox extension thanks to Web Extensions but there's too much unsupported code.

Thanks again and happy holidays to you and yours.

**Comment by bogenpirat** [comment]
if i really hated chrome/chromium, i'd probably port it myself. but that's just not the case at all, sorry. :)

thanks, and happy holidays to you as well.

**Comment by ktdd** [comment]
Sigh, I hate to bother you yet again but I found another bug probably related to this.

Add a torrent, write a directory name. Refresh, directory is still there. Delete said directory, refresh and this appears: http://i.imgur.com/Pb3VzCG.png - the deleted directory is still there too, under "null". If you delete "null" and said directory, they reappear after F5.

Latest version 1.2.8.5 from Chrome Web Store.

**Comment by bogenpirat** [comment]
sigh :-)

[remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/665077/remote-torrent-adder.git.zip)

let's try that one

**Comment by ktdd** [comment]
Works.
