### ISSUE TITLE
Feature request: Support for Qnap's Download Station

### ISSUE THREAD

**Issue by deadfreak** [bogenpirat/remote-torrent-adder#186]
Qnap NAS units come included with a torrent client called "Download Station" that uses libtorrent 0.16.17 as the backend. I assume this is just as similar to Synology (which you already support). If possible take a look at it :).

**Comment by bogenpirat** [comment]
i don't have access to one of those devices. pull requests are welcome.

**Comment by deadfreak** [comment]
Maybe this will help as well: https://github.com/cyclotron3k/qnap-download_station

**Comment by bogenpirat** [comment]
it gives a vague idea, but not nearly enough to do an implementation, and then there's still no way of testing it.

**Comment by deadfreak** [comment]
Assuming you find the api and make it, i don't mind testing an experimental browser addon :).
