### ISSUE TITLE
fails when adding to rutorrent inside web dir folder

### ISSUE THREAD

**Issue by adamwinn** [bogenpirat/remote-torrent-adder#188]
The address to get to my rutorrent webgui is 
```
http://xxx.zywie.bysh.me/rutorrent
````
If I enter
```
host: xxx.zywie.bysh.me/rutorrent
port: 80
```
It tries to connect to this url:
```
http://xxx.zywie.bysh.me/rutorrent:80/php/addtorrent.php
```
It puts the port number after the folder and not the hostname.

This is the correct url:
```
http://xxx.zywie.bysh.me:80/rutorrent/php/addtorrent.php
```

**Comment by bogenpirat** [comment]
then you'll wanna put "xxx.zywie.bysh.me" as host, "80" as port and "/rutorrent" as relative path.
