### ISSUE TITLE
Fix Server Type: Flood (Node.JS) (Borked Due to Labels Support Added Upstream)

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [bogenpirat/remote-torrent-adder#192]
Hello, 

Continuing #190;

The upstream FLOOD developer has _recently_ implemented support for adding labels when adding torrents / magnets (in fact; _very soon_ after you implemented FLOOD in RTA O_O).  

The underlying format / spec has changed, and as a result, has broken RTA's support of FLOOD. 

[Upstream PR](https://github.com/jfurrow/flood/pull/248), & [Upstream Issue](https://github.com/jfurrow/flood/issues/218)

The torrent-adding API / codepoints should be much more stable now, as they're pretty much feature complete, so hopefully, it won't need to be fixed again anytime soon. 

Thank you

-- Head Kangaroo
[KangarooCreativeTeam.com](http://kangaroocreativeteam.com)

**Comment by bogenpirat** [comment]
guess this is a good reminder to not overeagerly support immature software that still breaks their APIs (okay, i admit it's probably a bit mean to call it that) on a whim. 😉

7bebc84 fixes this, but without implementing label/tag support. feel free to open a new issue for support of that, but that'll not be high on my list of priorities for now. PRs will obviously be welcomed.

**Comment by KangarooCreativeTeam** [comment]
Hey, 

Just to follow-up; I've tested it, & confirm it's working great. 

I agree with your point; it's annoying that the API broke :( 

Fortunately; I don't think a breaking change like this should happen again anytime soon (I hope o_O)
If it does, I'll try to take a crack at it, & submit a PR :)

Thank you Julian

O_O
