### ISSUE TITLE
No torrents will add for Deluge and no message is shown

### ISSUE THREAD

**Issue by truckershitch** [bogenpirat/remote-torrent-adder#194]
Something changed either with Deluge or with my setup.  BitTorrent WebUI+ in Firefox gives errors now also, but that extension hasn't been updated since 2009 so there may be other issues going on there.

How can I enable debugging in your extension so I can try to trace this problem?  I can access the Deluge WebGUI from multiple browsers.   I only need a password for BitTorrent WebUI+, and not a username.

The rest of my programs are accessing Deluge with no problems at all; in fact, I just had a torrent uploaded 5 minutes ago.

Thanks!

**Comment by bogenpirat** [comment]
hah, debug mode! you must mistake me for a competent js dev.

get me a version deluge number and i'll take a look.

**Comment by truckershitch** [comment]
I'm running Deluge on Arch ARM, and the package filename is deluge-1.3.13+2+g6c73105-1-any.pkg.tar.xz.

**Comment by bogenpirat** [comment]
alright, that's the latest stable version.

i've tried 1.3.12 which seems to be the latest version available on ubuntu and that works fine.

1.3.13 from the official deluge ppa also works as expected. so unless the arch guys mess with the source code, it's looking more like a configuration issue than a new incompatibility. i know i haven't touched the deluge code in over two years (see a886a1b).

if you go to `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci`, enable the developer mode and then check the view for the background page of RTA, does it display any errors in the console when you try adding a torrent?

is there any error notification coming from RTA at all, or does it just fail silently?

**Comment by truckershitch** [comment]
Here is the log shown when I click on a torrent:
```
DelugeWebUI.js:8 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
RTA.clients.delugeAdder @ DelugeWebUI.js:8
RTA.dispatchTorrent @ functions.js:35
xhr.onreadystatechange @ functions.js:67
DelugeWebUI.js:9 POST https://192.168.1.44:8112/json 
RTA.clients.delugeAdder @ DelugeWebUI.js:9
RTA.dispatchTorrent @ functions.js:35
xhr.onreadystatechange @ functions.js:67
DelugeWebUI.js:9 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://192.168.1.44:8112/json'.
    at Object.RTA.clients.delugeAdder (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/webuiapis/DelugeWebUI.js:9:6)
    at Object.RTA.dispatchTorrent (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/functions.js:35:16)
    at XMLHttpRequest.xhr.onreadystatechange (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/functions.js:67:9)
RTA.clients.delugeAdder @ DelugeWebUI.js:9
RTA.dispatchTorrent @ functions.js:35
xhr.onreadystatechange @ functions.js:67
```

**Comment by truckershitch** [comment]
I got it -- I hadn't yet browsed to my server and had not accepted the certificate into Chrome.  It works now.

Sorry for the noise.

**Comment by bogenpirat** [comment]
ah well, shit happens. glad you got it working.
