### ISSUE TITLE
There is this error. is this a bug or normal occurrence.

### ISSUE THREAD

**Issue by brianjud** [bogenpirat/remote-torrent-adder#199]
![image](https://cloud.githubusercontent.com/assets/26887935/24637971/a9b2fee0-1917-11e7-9bae-ed6cc5c8da60.png)

**Comment by bogenpirat** [comment]
Obviously not normal. What you see there is a file not found error spat out by a web server. Some actual information about your rta configuration would be useful, but i suggest you review your configuration and check whether your relative path is correct.
