### ISSUE TITLE
Feature Request: Add Categories support for qBitTorrent v3.3x

### ISSUE THREAD

**Issue by bsdboy72** [bogenpirat/remote-torrent-adder#202]
It would be nice to specify what Category of the magnet link you send to qBitTorrent. 
The new 'Saving Management' part with the 'Default Torrent Management Mode - Auto' option. Keeping files organized is really easy. Context menu with categories would work fine.

**Comment by bsdboy72** [comment]
Have a sadly static way to do it manually with cURL:
# curl --data "username=USERNAME&password=PASSWORD&urls=MAGNETLINK&category=CATEGORY"  http://localhost:8080/command/download

Have a script where I manually add the torrent to qBitTorrent and set the CATEGORY, so the download goes in the "right" folder in the base dir.

I've searched for a way to implement it on my own, but I lack the programming skills needed :)
If this is the wrong place for this, please let me know.

**Comment by TravisCHoward** [comment]
I came here to ask for this exact thing.

**Comment by bogenpirat** [comment]
@lgos44 was kind enough to implement this in #207. gonna release it in a bit.
