### ISSUE TITLE
[Feature Request] Ability to Backup WebUI Information, Directory & Labels List

### ISSUE THREAD

**Issue by Spartinus** [bogenpirat/remote-torrent-adder#204]
Hi,
I was wondering if it would be possible to implement a feature like this. Whenever I clear my cookies, I end up having to start fresh. It would be amazing if something like this could be implemented. Thank you so much!

**Comment by bogenpirat** [comment]
where would you propose this backup goes? if chrome really deletes extension settings (i'd never considered that, that sucks), then it's a bit hard to save it elsewhere. you can already backup and restore settings using (this)[https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings] code from the wiki.

**Comment by TravisCHoward** [comment]
It should sync the settings just like every other Chrome extension does... to the account that's signed into Chrome.

**Comment by neil-bowers** [comment]
The settings are stored in an SQLite database; what I've been doing is backup up that database to Google Drive so I can synch it between my Chrome installs on different machines.

Some manual manipulation and digging are required though, so really it should back it self up the way other extensions do, to the user account logged in to Chrome.
