### ISSUE TITLE
Use native mac os notification when enabled in chrome

### ISSUE THREAD

**Issue by tarikd** [bogenpirat/remote-torrent-adder#205]
It's now possible to switch chrome so that it uses native macOS notification instead of the chrome notification system. Chrome 59 will even abandon it's notification system and use natively macOS notification.

Unfortunately even when I switch the use of macOS notification in the current chrome settings, remote torrent adder is the only plugin that still uses the old system.

**Comment by bogenpirat** [comment]
as per [this blog entry](https://blog.chromium.org/2017/05/chrome-59-beta-headless-chromium-native.html):

> In Chrome 59, when developers send notifications via the Notifications API or chrome.notifications, they will be shown directly by the macOS native notification system.

doesn't seem like there's a new api to be used for native notifications on the extension side, instead they'll just be displayed natively starting with chrome 59. have you tried that?

**Comment by tarikd** [comment]
I didn't try chrome 59 yet.

But on my current version of chrome (the latest stable release) I toggle the option to use native notification. All the notifications now go through macOS notification system, the only service that still uses the old notification is remote torrent adder.
________________________________

**Comment by bogenpirat** [comment]
well, as the blog post mentions, the chrome.notifications should be covered by that setting. i [use that](https://github.com/bogenpirat/remote-torrent-adder/blob/master/miscapis/functions.js#L92), so maybe you should give chrome canary a whirl and check whether it works there. i don't have any apply hardware, so i can't check.
