### ISSUE TITLE
support for CSRF-protection in qBittorrent 3.3.13+

### ISSUE THREAD

**Issue by bogenpirat** [bogenpirat/remote-torrent-adder#210]
as outlined by @abqnm in https://github.com/bogenpirat/remote-torrent-adder/issues/208#issuecomment-305673468, qbittorrent 3.3.13 implemented a few headers in their requests geared towards protecting against CSRF.

i'll try implementing a solution for the new version whilst still having fallback code for the new one.

**Comment by abqnm** [comment]
Thank you! Hopefully you can find a graceful way to do it. Having to fork off *another* branch for qBT servers  < 3.3.12, and have a legacy qBT server option would probably work too, but much less ideal than a solution that retains compatibility with both without having to have a separate branch for it.

**Comment by bogenpirat** [comment]
okay, i've done a minor re-write of the qBittorrent module.

in addition, since you can't set the "Referer" or "Origin" fields in XMLHttpRequest or the Fetch API, i've had to work around that by creating webRequest listeners that mess with the headers of webuis you set as type qBittorrent in your RTA settings. this required new permissions and in the past, you'd get a warning from chrome as soon as the extension updates. maybe they've made that quieter nowadays, i don't know. the update path might be a bit bumpy when this rolls into production, but it was really the only way to go.

i've tested the code for a copy of 3.3.7 (which should include functionality for versions going back as far as 3.2.x) as well as 3.3.13 (which is at the core of this issue). both worked fine. it's perfectly possible that versions older than 3.2.x no longer work, but since version checking with qBittorrent is such a god damn chore (and, weirdly, doesn't seem to work for the latest version), i'm hereby dropping support of RTA for qBittorrent older than 3.2.

i've pushed an updated version and am hoping i didn't mess up again. if so, let me know in a new issue.

**Comment by abqnm** [comment]
@bogenpirat Verified all is well now on 3.3.13.  Thanks for the quick fix!
