### ISSUE TITLE
qbittorrent category undefined issue

### ISSUE THREAD

**Issue by Wookie7** [bogenpirat/remote-torrent-adder#211]
I'm using Remote Torrent Adder 1.2.14 in Chrome on Windows 7 x64 to hand off torrents to qBittorrent 3.3.12 on Linux Mint x64.

This setup worked fine until a few days ago. Now, handing torrents off results in qBittorrent adding a catergory of "undefined" to the downloaded files. This causes qBittorrent to ignore it's default save path and write to /home/'user'/undefined/. 

Adding torrents into qBittorrent directly save files in the specified save path as normal. 

This leads me to the conclusion the communication from Remote Torrent Adder to qBittorrent is not dealing with torrent categories correctly. I have qBittorrent set to "Manual" torrent category management to just have files saved in one location only, which means I'm not using categories. 

I have tried using the "Label/Directory Interactivity" checked and unchecked with no change in behavior. 

Any suggestions as to a resolution?

Thanks for a cool extension and any help.

**Comment by bogenpirat** [comment]
yep, that's a dumb oversight introduced by a feature update. my bad. i've fixed it in code, but i'm currently working on another issue in the qBittorrent code, so i can't commit/push it just yet.

**Comment by Wookie7** [comment]
Thanks for the info!

**Comment by bogenpirat** [comment]
thanks for closing, just for the record the fix is part of a503e0da8e35038a737bbf8eb99dbd542d68db97. i'm pushing 1.2.15 to fix this now.
