### ISSUE TITLE
qBitTorrent CSRF requirements update in 3.3.13

### ISSUE THREAD

**Issue by SamEvansTurner** [bogenpirat/remote-torrent-adder#213]
Looks like the API has changed slightly for qBitTorrent in the latest update.

See https://github.com/Sonarr/Sonarr/issues/1956 and https://github.com/qbittorrent/qBittorrent/commit/087856d3d8d6d77881c3d8378a95d80d693af2dd

Every time you try to use the Remote Torrent Adder with qBitTorrent 3.3.13 it gives a 401 at the moment.

**Comment by SamEvansTurner** [comment]
Although it also looks like changes have been approved to reverse this, so might not be worth worrying about:

https://github.com/qbittorrent/qBittorrent/pull/6887

**Comment by bogenpirat** [comment]
let's wait a while then. :) i've already had a lot of "fun" with qbt, not particularly looking forward to dance around their design vims every other week.

we'll have to look at the work done in #208 and #210 once they settle on a decision. until then, please try sticking to 3.3.13 stable, which according to the latter issue should work.

**Comment by SamEvansTurner** [comment]
Ah I didn't see #208 and #210 - Hopefully qbt can work out the direction they want to go in soon. For the moment I've just dropped back to 3.3.12, since I still had a build lying around.

**Comment by Misiek304** [comment]
3.3.14 was released today and the issue is still present. I would appreciate if this would get fixed since I can't use WebUI at all at the moment.

**Comment by danpowell88** [comment]
Also having the issue with 3.3.14 in a docker container

**Comment by Misiek304** [comment]
3.3.15 and 3.4 BETA also have this issue.
Does anyone actually care about fixing this issue because I don't see a lot of interest here?

**Comment by bogenpirat** [comment]
i'll probably get around to it, seeing as they've apparently settled on their solution. just don't have a lot of time right now, so if anyone wants to spend their time writing a pull request, that'd go faster.

**Comment by Misiek304** [comment]
How's the work going?

**Comment by RedshirtMB** [comment]
I hate to just +1 a topic but I'd love to see some movement on this issue too.

**Comment by ArbiterGR** [comment]
Same problem here as well with 3.4 Beta 2.

**Comment by Misiek304** [comment]
Can we get a progress update on this issue please?

**Comment by robrien6** [comment]
Still not working for qbittorrent 4.04.  Is this ever likely to be fixed?  Qbittorrent is listed as supported on the chrome extension page, but it hasn't worked for half a year now.
