### ISSUE TITLE
uTorrent

### ISSUE THREAD

**Issue by kenfabio** [bogenpirat/remote-torrent-adder#214]
I can't add torrent to uTorrent WebUI, how I configure it? When I add, simply not happens, none message

**Comment by bogenpirat** [comment]
i always thought the directions on the options page were pretty concise. best bet is that you've entered the host or port details incorrectly.

for example, if you go to your webui by entering this in your browser:

```http://somehost.com:123/gui```

then for that example, `somehost.com` is the host, and `123` is the port. if you don't have a `:123` part in that place, just leave it at 80.

**Comment by kenfabio** [comment]
I put exactly like this, and path leave blank?

**Comment by bogenpirat** [comment]
yeah.

if you don't see any error messages with that setup, are you able to reach the utorrent webui in your browser? if yes, do you see any error messages after adding a torrent in the window that you reach under `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci`, having "developer mode" enabled and click on the "background page" link?

**Comment by bogenpirat** [comment]
okay, something clearly fails after roughly 2 seconds of waiting. if you could somehow get me the screenshot of the details you see after clicking on either of those failed requests, that might help. remember to black out sensitive data in them, like the Authorization header.

**Comment by kenfabio** [comment]
This?
![image](https://user-images.githubusercontent.com/30180342/28239110-423d8d34-693a-11e7-9daf-1625da01c979.png)

**Comment by kenfabio** [comment]
Oh thank you for attentio, I did some changes and works now, I re-installed the extension and re-configured
