### ISSUE TITLE
Rutorrent - server responded with an irregular http error code

### ISSUE THREAD

**Issue by 0mni** [bogenpirat/remote-torrent-adder#216]
The message I get when I enable developer for the extension and look at the background page.

`GET https://MYSERVER/php/addtorrent.php?result[]=Success&name[]=1500597865574.torrent& 404 ()        functions.js:9 
  | XMLHttpRequest.sendAsBinary | @ | functions.js:9
-- | -- | -- | --
  | RTA.clients.ruTorrentAdder | @ | ruTorrentWebUI.js:65
  | RTA.dispatchTorrent | @ | functions.js:24
  | xhr.onreadystatechange | @ | functions.js:69`

This may be a duplicate, however, I checked thorugh a few other threads and they seem to be on a different track, I may be wrong.

I get the error any time I add a new torrent, occurs 100% of the time.  I recently migrated to a docker version of rtorrent/rutorrent.  I no longer have rutorrent being served by the main nginx server, it is not doing a reverse proxy to another nginx server, I don't like it but it does work, running inside docker that serves the rutorrent.  I can access rutorrent without any issues, works perfectly fine, even if I add a torrent, it still functions without any issues.  However, I get that nasty annoying error message whenever I add a torrent.  I can see what the issue is, its calling for the success message prompt, but at the wrong url.  Currently its looking at:
https://MYSERVER/php/addtorrent.php?result[]=Success&name[]=1500597865574.torrent&
But it should be looking at:
https://MYSERVER/rutorrent/php/addtorrent.php?result[]=Success&name[]=1500597865574.torrent&

If I goto the correct page, I get a JSON response "Success" message.

I do have "/rutorrent" in the settings for the relative path, but I am not sure how the "success" message url is generated.

Any suggestions or tips would be appreciated.

**Comment by bogenpirat** [comment]
alright, seems a bit weird and could have to do with your server setup. but let's step through a few things first:

please take a look at the network tab after opening the background page's inspection window, then add a torrent. there'll be a request to the server the torrent file is on, then a POST where it sends the torrent and another GET stemming from a redirect from the previous request to the success page. since you appear to be seeing issues for that last request, it may make sense to check the response headers on the second request, specifically the "location" response header. does the server send you to the wrong place?

also, you write that you can use the webui fine in the browser, but can you check whether you can actually add a torrent file with it?

**Comment by 0mni** [comment]
> content-type:text/html; charset=UTF-8
date:Fri, 21 Jul 2017 10:14:49 GMT
location:/php/addtorrent.php?result[]=Success&name[]=1500632088927.torrent&
server:nginx
status:302
x-powered-by:PHP/7.1.4

The response header is coming back without the /rutorrent location, is there any reason why Torrent adder is using the response header location without checking to see if the relative dir is part of the response?

Anyway, I did a little "magic" with the two nginx configurations.


I am now accessing the docker nginx with this url reverse proxy configuration:
```
         location ^~ /rutorrent {
                proxy_pass              http://172.17.0.2:9080/rutorrent;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto       $scheme;
                proxy_redirect off;
        }
```
And my docker configuration is now using:
```
worker_processes  auto;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  off;
    error_log       /config/nginx/error.log crit;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout  65;

    client_max_body_size  25m;

    gzip             off;

    server {
        listen       9080;

        root /usr/share/webapps;

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_intercept_errors        on;
            fastcgi_ignore_client_abort     off;
            fastcgi_connect_timeout         60;
            fastcgi_send_timeout            180;
            fastcgi_read_timeout            180;
            fastcgi_buffer_size             128k;
            fastcgi_buffers                 4       256k;
            fastcgi_busy_buffers_size       256k;
            fastcgi_temp_file_write_size    256k;
            fastcgi_pass          127.0.0.1:7777;
#            include               fastcgi.conf;
        }

        location /RPC2 {
            include scgi_params;
            scgi_pass 127.0.0.1:5000;
        }
    }
}
```
I no longer get the dreaded "irregular http error code" message, and everything looks good in the background tab.  Hope this helps someone else out, maybe we can make Torrent Adder idiot proof by checking if the success url includes the relative path 😃
