### ISSUE TITLE
Feature Request: Please add support for "tTorrent"

### ISSUE THREAD

**Issue by Urzy911** [bogenpirat/remote-torrent-adder#219]
Feature Request: Please add support for "tTorrent" android client.

**Comment by bogenpirat** [comment]
done in fe41ba2. might be a while before i release that though.

in the meantime you can try it out: https://github.com/bogenpirat/remote-torrent-adder/archive/master.zip

howto: https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code

**Comment by Urzy911** [comment]
Hi,

I get this error... because the script tTorrentWebUI.js in webuiapis folder is missing.

Failed to load extension from: ~\Downloads\remote-torrent-adder-master
Could not load background script 'webuiapis/tTorrentWebUI.js'.

**Comment by bogenpirat** [comment]
sorry, i messed up the commit. fixed in 6f4a4ab. zip to try is under the same url.

**Comment by Urzy911** [comment]
Hi,
now it's working, thanks.
Torrent is added to queue, but it shows an error: Server responded with an irregular HTTP error code....

![image](https://user-images.githubusercontent.com/32169897/30781603-82e24ecc-a122-11e7-99cf-319ae2604c37.png)

**Comment by bogenpirat** [comment]
tested it again in preparation for the 1.3.x releases - looked like it's working.
