### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by liquidox** [bogenpirat/remote-torrent-adder#222]
One of the main reasons I wont switch to FF Quantum is the lack of this perfect addon.

It seems it's also not compatible with Chrome Store Foxified.

Any chance to get an FF version or to have this made compatible?

**Comment by Zer0b0x** [comment]
Hello,

I'm the same case, i love your plugin but without an compatibility on firefox i keep using chrome.

do you have plan to update it to use it on firefox 57 and above ?

thanks you

**Comment by bogenpirat** [comment]
i've no interest in (let alone the time to) making this plugin cross-browser, sorry.
