### ISSUE TITLE
Feature request: Clone server

### ISSUE THREAD

**Issue by Litz97** [bogenpirat/remote-torrent-adder#223]
I am setting up a server for every category of download (film, tvshow, game etc.) to sort it into folders right away. I have to enter the same info every time. A clone server feature would be very helpful

**Comment by bogenpirat** [comment]
that's a creative way of approaching the label issue. but i don't see it as a feature that would be used very much.

one way of doing this manually would be to go to the extension's options page and running this code from the developer tools window/pane (F12):

```javascript
var servers = JSON.parse(localStorage.servers);
servers.push(servers[0]);
localStorage.setItem("servers", JSON.encode(servers));
```

where the "0" in line 2 is the index of the server you want to clone, starting from 0, and starting from the left in the servers overview. you can re-run the code as often as you want copies.
