### ISSUE TITLE
Doesn't catch some magnet urls without right clicking

### ISSUE THREAD

**Issue by bassmadrigal** [bogenpirat/remote-torrent-adder#224]
I love using this extension and it makes things a lot easier since my server is upstairs and I like to add torrents from my laptop downstairs... but I'm running into a minor annoyance with magnet links from eztv.ag (like this [Nova ScienceNOW](https://eztv.ag/shows/201/nova-sciencenow/) page). I can't seem to left-click them and have them added. I have to right-click and manually select "Add to Remote WebUI". When I do this, it pops up the notification and it loads in my torrent client. The odd thing is magnet links to add an [Arch ISO](https://www.archlinux.org/download/) works fine.

I tried to add some link catching, but it didn't make a difference. The code I used was `magnet\:\?`

This is using Chrome 62.0.3202.94 (64bit) on Windows 10, using transmission 2.92 on a remote server (although on the same LAN) running Slackware 64 14.2.

**Comment by Misiek304** [comment]
+1 for that one.

**Comment by bogenpirat** [comment]
this seems to work fine for me now. what happens with some pages is that they dynamically generate links via javascript, which the content script in RTA cannot catch currently (and there's no reasonably fast mechanism to make it do that, honestly). in those cases, i'm afraid you'll have to go with the context menu.
