### ISSUE TITLE
When used to send to rutorrent, rutorrent doesn't get the date when the torrent was added.

### ISSUE THREAD

**Issue by piperun** [bogenpirat/remote-torrent-adder#226]
So if I let remotetorrent add it automatically to my own seedbox, then it doesn't show when the torrent was added nor is the labels added (could be rutorrent though), before it worked with a now obsolete firefox addon: bittorrent-webui+.

So I'm pretty sure it's isn't rutorrent's fault in this case (at least with not having a date added).

**Comment by bogenpirat** [comment]
works just fine for my rutorrent setup.
sounds more like something on the seedbox's end was changed, i've not touched RTA in a few months.

**Comment by piperun** [comment]
Hmm yeah then that sounds quite odd, which rutorrent version + rtorrent version are you running? 
I'm running:
v3.8 rutorrent 
0.9.6-2build1 rtorrent
and I'm using vivaldi (which has a little bit of a weird way of adding torrent files, since it'll cause their dl prompt to pop up). 
You don't think it has to do with how RTA grabs + insert the torrent file?

**Comment by adamwinn** [comment]
This sometimes happens with rutorrent.  If you google, you can find some fixes.  One is to change the date format display in the settings and any new torrents should have the date added.  Another option is to Edit the torrent but dont change anything and press OK, most of the time the added date will then be set.
