### ISSUE TITLE
Allow left click to launch the Remote UI

### ISSUE THREAD

**Issue by Ryrynz** [bogenpirat/remote-torrent-adder#229]
Right and left click do the same thing launching the context menu. Allow left click to launch the Remote Ui in either the current tab or new tab.

**Comment by Mavi222** [comment]
I would also like to quickly access the Remote UI. It would save me one home shortcut space and it would make everything quicker.

**Comment by Ryrynz** [comment]
Hey Bog, this is a simple addition, can you get this in there? Other remote torrent extensions provide this functionality.

**Comment by bogenpirat** [comment]
yeah, should be doable.

**Comment by Ryrynz** [comment]
We do, but this is using "precious" bookmark bar space for me and currently there's no functionality assigned to this extension by clicking on it either, every other extension in my browser does something when clicked on.
