### ISSUE TITLE
Yggtorrent.is and z-index css property of the modal window

### ISSUE THREAD

**Issue by aztazt** [bogenpirat/remote-torrent-adder#232]
Could you please set a higher z-index value to the modal window for the torrent website called "yggtorrent.is", because the modal window appears behind of all others.
Thank you.

https://imgur.com/a/u3fwG

**Comment by clemart3** [comment]
Hi Aztazt, do you have find a solution for z-index problem on Ygg website ? Thank you

**Comment by aztazt** [comment]
Non désolé, rien trouvé pour l'instant (pas eu le temps de chercher). En attendant, j'utilise Xirvik

**Comment by thibaut129** [comment]
Same problem. I have many bug with Xirvik and rutorrent 👎

**Comment by thibaut129** [comment]
I fix it #238.
If you want you can check my fork repo to pull and test it.

Enjoy 👍
