### ISSUE TITLE
Feature Request: Add support for Epic Browser

### ISSUE THREAD

**Issue by maxtakular** [bogenpirat/remote-torrent-adder#233]
Would it be possible to adapt this to work with Epic Browser?  Epic is Chrome/Chromium based, yet the Remote Torrent Adder extension install page does not recognize it and therefore does not allow installation.  Thanks.

**Comment by bogenpirat** [comment]
sorry, but epic browser doesn't support chrome extensions at all. this is a chrome extension and i don't plan on supporting other browsers for now.
