### ISSUE TITLE
401 error with qbittorrent WebUI in 4.04 when Remote Adder is setup properly on local network

### ISSUE THREAD

**Issue by seanbperiod** [bogenpirat/remote-torrent-adder#234]
I cannot access WebUI when Remote Adder is configured. If I change the port number in RTA to something other than it should be, I can access WebUI fine; but once it's set to the same port number, I get 401 errors. 

This is for qbittorrent installed on Windows and being accessed within the same network. 

However, when accessing another remote computer with qbitorrent on a different network, it works fine. 

The same thing also happens when I had Transmission installed on the other server. I'm unable to access the WebUI once the port is configured in RTA.

**Comment by seanbperiod** [comment]
Update:

So weird thing I noticed. If I make a duplicate of the same entry, but leave it at the end of the list of servers, it will work. However, if I move it to the front to be the default, it will 401.

**Comment by andrelx** [comment]
seanbperiod - thanks for finding a workaround !!

André

**Comment by bogenpirat** [comment]
yeah, that's funky. does it still happen? give #254 a try. if not, respond here with a backup of your settings, cf. https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings
remember to replace your sensitive data from it with placeholder values.

**Comment by mattpurnell** [comment]
Hi - I can confirm it is happening to me; even with authentication bypass (local subnet) on the qBittorent server.


![image](https://user-images.githubusercontent.com/35792584/73464396-b74aef00-43e3-11ea-98b8-198af4d5a980.png)

I usually use a reverse proxy (NGINX) but I bypassed for troubleshooting - same result. I have tried with and without credentials, with and without the authentication bypass.

Versions:
qBittorrent v4.2.1 Web UI (64-bit)
Remote Adder version ?? Added on 31/01/2020

`"{"servers":"[{\"name\":\"qbit\",\"client\":\"qBittorrent WebUI\",\"host\":\"dsm.lcl\",\"port\":\"8080\",\"hostsecure\":false,\"login\":\"qadmin\",\"password\":\"#######\",\"qbittorrentdirlabelask\":true}]","catchfromcontextmenu":"true","popupduration":"2000","catchfrompage":"true","showpopups":"true","linkmatches":"([\\]\\[]|\\b|\\.)\\.torrent\\b([^\\-]|$)~torrents\\.php\\?action=download","linksfoundindicator":"true"}"`
