### ISSUE TITLE
Feature request: per-torrent-host label/dir settings

### ISSUE THREAD

**Issue by emptied** [bogenpirat/remote-torrent-adder#237]
It would be really cool if RTA could have a user configuration list something like: hostnamepattern:(label, directory) , where RTA defaults to label and directory when a torrent is dled from a site in the list.

**Comment by bogenpirat** [comment]
implemented something like this in 7826a3233e79d219658045eb299b2d6134aadaf3. i'm gonna have to dick around with that further though, since either it or the modal label/directory dialog should take precedence. not sure about that yet.

**Comment by adamwinn** [comment]
I'd love to see something like this implemented

**Comment by JPRuskin** [comment]
Your fix worked for me, @bogenpirat - looking forward to it being released (this was something I was thinking of trying to implement, at one point, so super glad to see it's already here).

**Comment by bogenpirat** [comment]
well, it's released now. at least for ruTorrent.

**Comment by emptied** [comment]
That works for me, thank you!
