### ISSUE TITLE
rutorrent - server didn't accept data: 200

### ISSUE THREAD

**Issue by fxjkhr** [bogenpirat/remote-torrent-adder#239]
I get the following error when I attempt to add a torrent with the extension

![error popup](https://user-images.githubusercontent.com/780260/42415301-950f4e70-81fe-11e8-91e9-892ef523e9a3.PNG)

![server settings](https://user-images.githubusercontent.com/780260/42415306-a7764b7c-81fe-11e8-857f-df6369b33c16.PNG)

I get this error with both the extension on the chrome store (Version: 1.2.15 / June 4, 2017) and with the unpacked extension from the github (July 7, 2018).
my rtorrent client is running from a docker image for unraid os on my local network https://github.com/binhex/arch-rtorrentvpn (version 0.9.7/0.13.7)

**Comment by fxjkhr** [comment]
Using the build here solved my issue: https://github.com/bogenpirat/remote-torrent-adder/issues/198#issuecomment-292947392

**Comment by maki-chan** [comment]
Works with the build from #198 which is unfortunately an old version. Will there be a fix? My current workaround is unfortunately to not use the Torrent Adder which isn't a solution at all.

**Comment by kingdazy** [comment]
This extension seems to be dead.

> I get this error with both the extension on the chrome store (Version: 1.2.15 / June 4, 2017) and with the unpacked extension from the github (July 7, 2018).

> My current workaround is unfortunately to not use the Torrent Adder which isn't a solution at all.

Same error here.
