### ISSUE TITLE
Feature request: Please add download directories option to context menu, similar to Utorrent easy client

### ISSUE THREAD

**Issue by ChickenDipper1** [bogenpirat/remote-torrent-adder#240]
Please add download directories option to context menu, similar to Utorrent easy client.
This would make it so much better to use for me!
Thanks.

**Comment by bogenpirat** [comment]
i'm guessing you want this for µTorrent?

for ruTorrent, we solve this with a modal dialog. feel free to re-open a ticket to extend the modal dialog to utorrent (idk if the api even allows for that), but i'm not going to extend the context menu for this.
