### ISSUE TITLE
Label/Directory interactivity - Qbittrorrent

### ISSUE THREAD

**Issue by ChickenDipper1** [bogenpirat/remote-torrent-adder#241]
Hi,

This option does not work when using the right click context menu option to add a torrent, only when the the link is caught by clicking on the links, any chance of a fix please? :)

**Comment by quisp65** [comment]
This comes in handy when you are on a website where the magnet link is hidden with lots of paying ads.   Left clicking gives you the trickery and BS ad site.... where as right clicking and sending it your choice directory creates no harm if you right clicked on the wrong spot.

**Comment by bogenpirat** [comment]
should've been fixed in d791c14f646fd88aa62f8884304e37e35dc2ee42
