### ISSUE TITLE
Settings Deleted

### ISSUE THREAD

**Issue by madorian** [bogenpirat/remote-torrent-adder#246]
This has happened 3 times in the last two/three years, that all my settings were deleted. This is not your fault, cause all settings from all other extensions were deleted as well. It only pertains to settings of the extensions; all my bookmarks and such are ok. 

Anyways, if you've seen this issues yourself, is there any way I can extract the old settings from the profile? 

If not, then just close this issue. Worth a try to figure out what's happened;)

**Comment by scornelius1** [comment]
Ive had the same thing happen to me but none of my other extensions were impacted. The data for the extension is stored in local storage so something must have wiped that out. Once that datas gone and youre seeing the default values for the extension i dont think theres anything you can do to retrieve it however if you get setup again and want to save your settings you can do the following to backup your configuration:

1) open up web developer tools when you are on the extension options page
2) go to the application tab
3) under local storage select the chrome extension in the drop down
4) you should have a list of key values, double click the value for "servers" and save the json string
5) if youre settings get wiped out again you should just need to go in and replace the default value for servers with your saved one and your server config will be restored

equally you can save any of the other vaules if youve changed them. Hope this is helpful for next time

**Comment by piperun** [comment]
You can try my fork that specifically address that problem.

**Comment by bogenpirat** [comment]
sorry, i've never had this happen before and can't imagine why it would, unless it happens to other extensions as well.

one way of backing up settings is described here: https://github.com/bogenpirat/remote-torrent-adder/wiki/Backup-&-Restore-settings

alternatively, give piperun's fork a try. he focuses on synchronizing settings via the google account.
