### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by fingerboxes** [bogenpirat/remote-torrent-adder#247]
The addon installs just fine in Brave, but doesn't seem to work. Configurations that work in Chrome for Deluge and Flood throw 'irregular http response' in Brave.

**Comment by zxsix** [comment]
+1

**Comment by ryanerwin** [comment]
This is a bug in brave, not in remote torrent adder...

You can get it to work the way you expect... Just need to use the new flag (in latest version)

```
brave --disable-webtorrent-extension
```
