### ISSUE TITLE
Recently updated to qbittorrent 4.1.5 and seem to be getting a HTTP 403 error code.

### ISSUE THREAD

**Issue by 1sourCream** [bogenpirat/remote-torrent-adder#249]
As title says. I also have not tried to revert back to 4.1.4 However i have no problem getting access to web gui on other devices.

**Comment by FirstGeekDanny** [comment]
Downgrade to 4.1.4 fixes the issue...

**Comment by bmtphoenix** [comment]
+1, downgrading to 4.1.4 fixed. Grabbed it from here - https://www.neowin.net/news/qbittorrent-414/. I didn't see a link to previous versions on the official site, but I could've missed it.

**Comment by Ryrynz** [comment]
So has anyone chased up why this isn't working? Is it the client or does the extension need updating.. 4.1.5 had some changes in this section.

**Comment by pax0707** [comment]
I just reverted to the previous build.
Guess they changed something in webui.

**Comment by Litcube** [comment]
Here's +1 for hoping for a fix!

**Comment by chewcrunchyice** [comment]
I got it working after unchecking the option for "Enable Cross-Site Request Forgery (CSRF) protection)" in Options > Web UI > Security

**Comment by chewcrunchyice** [comment]
What I did was uncheck Enable Host header validation, hit Apply, tested, didn't work, checked Enable Host header validation, unchecked Enable Cross-Site Request Forgery (CSRF) protection, hit apply.
Maybe somehow that process did something different. Haven't restarted qbt after changing settings or since.

**Comment by Ryrynz** [comment]
All I did was unchecked Enable Cross-Site Request Forgery and it worked.

**Comment by mastachaos** [comment]
Messing with these settings doesn't seem to make a difference for me.

**Comment by Wookie7** [comment]
@chewcrunchyice 
Unchecking Enable Cross-Site Request Forgery worked for me. Thanks!

For others info, qBittorrent is running on a Linux Mint machine and the WebUI was on a Windows 7 machine in both Chrome and Firefox.

**Comment by sirloinofbeef** [comment]
Unchecking Enable Cross-Site Request Forgery didn't work for me :(
server run on Windows 10
client run on Windows 10 with Chrome browser

**Comment by jobrien2001** [comment]
There is a fork with a fix for this issue and future versions of Qbittorrent.  WOuld be great for someone to compile that and post it somewhere or merge it into here.

https://github.com/tjjh89017/remote-torrent-adder/commit/0a364ea7f08d8150d877b7f455791ce29e828f19

**Comment by bogenpirat** [comment]
let's move this to #254.
