### ISSUE TITLE
Error code 0

### ISSUE THREAD

**Issue by Daniel-PT** [bogenpirat/remote-torrent-adder#250]
Hi all.
I use Qbittorrent. Was on 4.1.5 but downgraded to 4.1.4 but no change.
I havent changed eneyting. Now im getting a error code 0.

Tryed disable the extension and enable again.

What can i do?

Regards Daniel

**Comment by mastachaos** [comment]
I too am having this issue after updating to 4.1.5 

Interestingly enough, if I use it from outside my LAN, it still works (using domain name and port), but on my LAN, using the domain name or the local IP, it always returns error code 0.

**Comment by bogenpirat** [comment]
please refer to #254 for now.
