### ISSUE TITLE
How to troubleshoot with qBittorrent 4.1.4

### ISSUE THREAD

**Issue by MisterKurtz10** [bogenpirat/remote-torrent-adder#251]
It was all working fine until I had to rebuild the PC. I am using port 8081 on QB and I have double-checked it. The WebUI works, so I know the port is open.

From a Jackett search results list, I used to be able to right click a link and send it to QB. Now, I get a Chrome notification says "The server sent an irregular HTTP. error code 0"

How do I go about troubleshooting this? Is there a log I can look at?

**Comment by ctwiner** [comment]
I have exactly the same behavior.  I'm running on port 8080 on an Unraid server and since updating remote torrent adder will not add to download.  I've tried every combination (including whitelisting LAN)to no effect.  Did something change that is blocking remote torrent adder?

**Comment by jobrien2001** [comment]
> I have exactly the same behavior. I'm running on port 8080 on an Unraid server and since updating remote torrent adder will not add to download. I've tried every combination (including whitelisting LAN)to no effect. Did something change that is blocking remote torrent adder?

White listing does work if you leave the admin and pw blank on the extension.  I am using the linuxserver docker.

**Comment by zacharygoold** [comment]
> White listing does work if you leave the admin and pw blank on the extension. I am using the linuxserver docker.

This fixed it for me, thanks!

**Comment by bogenpirat** [comment]
not 100% sure, but it should be related to #254. please try that and let me know if that does (not) fix it.
