### ISSUE TITLE
Windows 1903 notification issue

### ISSUE THREAD

**Issue by bobsage123** [bogenpirat/remote-torrent-adder#256]
I just started having an issue after upgrading to 1903. When I get a notification it will appear for a split second in my notification center then disappear. It does not make a sound anymore and it doesn't pop up in the bottom right like it used to. I'm on chrome  74.0.3729.75 beta.

**Comment by GithubMarcel** [comment]
Same here, Chrome version 74.0.3729.108 (Official Build) (64-bit)  OS=W10 1809

**Comment by GithubMarcel** [comment]
This fixed it for me: Check if you have Google Chrome notifications enabled in Windows. Go to configurations > notifications & actions and enable notifications.

**Comment by bobsage123** [comment]
> This fixed it for me: Check if you have Google Chrome notifications enabled in Windows. Go to configurations > notifications & actions and enable notifications.

I do, that's whats odd about it. All the settings are set how they used to be.

**Comment by bogenpirat** [comment]
this is not something that RTA can control. at best, it's a windows issue (i'm sure there are settings somewhere for this), at worst you'll have to check what you can configure in chrome itself.

**Comment by bobsage123** [comment]
This issue fixed itself on its own over time.
