### ISSUE TITLE
Extension ONLY works in qbit version 4.1.4 or older...

### ISSUE THREAD

**Issue by Jynx2120** [bogenpirat/remote-torrent-adder#257]
For me updating qbit to anything above version 4.1.4 breaks this extension in Chrome. I've installed qbit version 4.1.5 and 4.1.6 and both break the extension. All I get is a red popup message saying it failed. Currently I'm sticking with qbit version 4.1.4, this is the last known version to continue to work with this extension in Chrome. Prior to qbit 4.1.5 there were no issues at all.

I'm running everything on Windows 10.

**Comment by sirloinofbeef** [comment]
This has been an issue for seeral months:
https://github.com/bogenpirat/remote-torrent-adder/issues/249

**Comment by Jynx2120** [comment]
I'm still having this issue. Is there a current fix for this problem? The only version of qBit that works for me is 4.14.

**Comment by bogenpirat** [comment]
please refer to #254 for now.
