### ISSUE TITLE
Unable to add torrents Chrome/Deluge/Ubuntu

### ISSUE THREAD

**Issue by neuman1812** [bogenpirat/remote-torrent-adder#259]
Trying to add magnets to remote torrent adder and nothing happens.  I pulled up the console and this was the only error comming up when I clicked on the magnet link.  I tested this on a few different trackers and its the same across all of them.  Popups and firewalls were temporarily disabled  for testing with no change.

jquery-1.11.0.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

OS: Ubuntu 18.04
Chrome: Version 77.0.3865.75 (Official Build) (64-bit)
Deluge Webui Hosted Locally.

**Comment by bogenpirat** [comment]
the warning you've pasted is a just that; a warning. you can ignore it for now.

that being said, i cannot reproduce your issue. working fine here under chrome 77.0.3865.90 with deluge running on ubuntu. are you sure about your settings? attached is a screenshot of mine, perhaps yours contain invalid data. 
![image](https://user-images.githubusercontent.com/1835496/65562485-eee1f000-df46-11e9-99d7-41f32e61e542.png)
