### ISSUE TITLE
failed to auth

### ISSUE THREAD

**Issue by FernandoMiguel** [bogenpirat/remote-torrent-adder#262]
```
Request URL: https://XXXX/rutorrent/php/addtorrent.php?&torrents_start_stopped=1
Request Method: POST
Status Code: 401 Unauthorized
Remote Address: 18.XXX.XXX.XXX:443
Referrer Policy: strict-origin-when-cross-origin
Connection: Keep-Alive
Content-Length: 469
Content-Type: text/html; charset=iso-8859-1
Date: Sat, 26 Oct 2019 12:55:17 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.18 (Ubuntu)
WWW-Authenticate: Basic realm="Authentication required"
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,pt;q=0.8
Connection: keep-alive
Content-Length: 408
Content-Type: application/x-www-form-urlencoded
DNT: 1
Host: XXXXXX
Origin: chrome-extension://oabphaconndgibllomdcjbfdghcmenci
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
(empty)
torrents_start_stopped: 1
```

Google Chrome | 78.0.3904.70 (Official Build) beta (64-bit)

**Comment by bogenpirat** [comment]
that looks like the first request to the webui which doesn't necessarily show failure, but the challenge to provide credentials by the server (see WWW-Authenticate header). there should be another following it that actually fails (shows up red in the network view of the inspector). this one looks fine.

are you sure you've entered your credentials correctly?

**Comment by FernandoMiguel** [comment]
@bogenpirat  no other entry on devtools.
creds are copy paste and worked with another  extension
https://chrome.google.com/webstore/detail/torrent-clipper/cmhdhpcfabppigjedlenkmleklplflhp

**Comment by bogenpirat** [comment]
hmm.. might be due to the CORS directives. mind trying out this build
[remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/5012915/remote-torrent-adder.git.zip) with [these](https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code) instructions?

**Comment by zeroalias74** [comment]
> hmm.. might be due to the CORS directives. mind trying out this build
> [remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/5012915/remote-torrent-adder.git.zip) with [these](https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code) instructions?

I was able to use this version and install on Edge: Version 84.0.522.50 (Official build) (64-bit)
With the version from the chrome store, I had all sorts of issues from torrents not adding/loading, error messages, sometimes no notifications, etc. Installed the version referenced and everything is back to working, no issues found so far. Everything is working as it should. Please update if this build gets pushed at some point to official chrome web store, so I can reinstall via the store if needed. Thanks again!
