### ISSUE TITLE
Magnet links 

### ISSUE THREAD

**Issue by B-Mqn** [bogenpirat/remote-torrent-adder#263]
i cant seem to get it to handle magnet links.
if i right click the magnet link and select the the remote torrent adder it add fine

**Comment by bogenpirat** [comment]
from your description it would seem that the website in question generates the link via javascript only **after** the page has loaded and RTA's has already run, evading detection. does it work fine for the magnet link in the lower right pane here? (it's a link to a ubuntu linux iso)

https://jsfiddle.net/u2jea06n/

**Comment by neoOpus** [comment]
This cannot be fixed somehow? to make it work on http://audiobookbay.nl/ ?
