### ISSUE TITLE
Qbittorrent 4.1.7 x86 not work

### ISSUE THREAD

**Issue by wutongskype** [bogenpirat/remote-torrent-adder#265]
![Snipaste_2020-01-02_19-12-15](https://user-images.githubusercontent.com/40192806/71665500-2824ca00-2d98-11ea-8dee-362ff3e275e5.jpg)

![Snipaste_2020-01-02_19-43-25](https://user-images.githubusercontent.com/40192806/71665504-2a872400-2d98-11ea-92ae-d39b8ed19a78.jpg)

**Comment by JDLessl** [comment]
I get the same issue with qBitTorrent 4.2.1

**Comment by bogenpirat** [comment]
addressed in eeed8677082b9875a836d73896212d29b74a0efa and 8fd58b22e0854c27bc1f3dbf501df937f5ebe0b0; will be fixed by the next release.

**Comment by Terebi42** [comment]
This works for me now. NOTE: YOU HAVE TO RECREATE YOUR CONFIG using the new qbit 4.1+ option, your old setup will not magically start working.
