### ISSUE TITLE
qbitorrent not working with remote torrent adder

### ISSUE THREAD

**Issue by rchchmpgn** [bogenpirat/remote-torrent-adder#267]
the chrome addon 'remote torrent adder' has never worked for me since using qb. utorrent works but crashes all the time. is there another method of sending torrent and magnets to remote webui?

currently using qbittorent 4.2.1

**Comment by mzhboy** [comment]
I can confirm this bug too

**Comment by zybexXL** [comment]
This is due to QBittorrent's API v2 change. There's a temporary fix until a new version is released:
https://github.com/bogenpirat/remote-torrent-adder/issues/253#issuecomment-534719033

**Comment by mzhboy** [comment]
> This is due to QBittorrent's API v2 change. There's a temporary fix until a new version is released:
> [#253 (comment)](https://github.com/bogenpirat/remote-torrent-adder/issues/253#issuecomment-534719033)

thanks，I'm now using this temporary solution and it works fine.

**Comment by rrrevin** [comment]
Until @bogenpirat issues a fix, see here for a working solution: https://github.com/bogenpirat/remote-torrent-adder/issues/253#issuecomment-581017176
