### ISSUE TITLE
http error: 0 - rutorrent 

### ISSUE THREAD

**Issue by RichardBarrett** [bogenpirat/remote-torrent-adder#268]
Remote Torrent Adder has started failing with http error 0. Torrents are not being added to rutorrent.

Here's the error report...

ruTorrentWebUI.js:65 POST https://xxx:xxx@xxx/rutorrent/php/addtorrent.php? net::ERR_CERT_COMMON_NAME_INVALID
XMLHttpRequest.sendAsBinary @ functions.js:9
RTA.clients.ruTorrentAdder @ ruTorrentWebUI.js:65
RTA.dispatchTorrent @ functions.js:24
xhr.onreadystatechange @ functions.js:69
XMLHttpRequest.send (async)
RTA.getTorrent @ functions.js:76
RTA.genericOnClick @ functions.js:156
(anonymous) @ extensions::contextMenusHandlers:79

**Comment by gcaliber** [comment]
I don't know if there is a way to fix the addon, but in chrome if you disable chrome://flags/#out-of-blink-cors it fixes the error.

**Comment by RichardBarrett** [comment]
This appears to have solved itself. I have no idea how. Four days of this issue then all ok again.
