### ISSUE TITLE
Can RTA save torrents without adding? 

### ISSUE THREAD

**Issue by damagu** [bogenpirat/remote-torrent-adder#272]
Instead of having RTA add torrents to a torrent client, can it be configured to save torrent files to a directory which is scanned by the torrent client?
I ask because I'm using ruTorrent and I have autotools set to scan and add torrents from a watch directory, keep them in a seeding directory while active and move them to a completed directory when done. This is working properly for torrents which autotools finds in the watch directory. But, autotools is not moving completed downloads if the torrents were added via RTA. I suspect autotools is only moving files which it added and it's ignoring the ones added by RTA. So, if I can get RTA to save to the watch directory without adding, then I believe that because the adding will be done by autotools it should do the move on complete as well.

**Comment by JPRuskin** [comment]
This would be harder to do, particularly unless you're saving locally (which I suspect isn't what most users are using this plugin for, though I may be wrong).

Most of the server types that I've seen in this extension interact with the client via HTTP(S) calls, which don't need you to expose a filesystem (which would be required for you to save the .torrent files to a directory.)

Having said that, rTorrent's Autotools is working for me, despite my using RTA to add all torrents.

**Comment by damagu** [comment]
I suspected that it might not be possible. I wonder why autotools is working for me with the torrents uploaded from my media centre but not for the ones added by rta. Can you tell me how your autotools is configured?

**Comment by bogenpirat** [comment]
in order to save data anywhere, RTA would require access to a file system, which is not something that chrome extensions get from the chrome API; this is by design.

by that logic, unfortunately your request does not fit into the scope of this extension and you might want to look into another solution for your use case.
