### ISSUE TITLE
Flood is broken

### ISSUE THREAD

**Issue by TimCook1** [bogenpirat/remote-torrent-adder#274]
The extension is currently broken with flood.  There may be *other issues* but at the very least in floodWebUI.js - lines 18, 33, and 40 are attempting to make API calls, but not using the /flood subdirectory, so it just straight fails.  If I add "/flood/" to the front, it works as expected

```
	xhr.open("POST", scheme + server.host + ":" + server.port + "/flood/auth/authenticate", false);
	xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
	var loginMsg = JSON.stringify({"username": server.login, "password": server.password});
	xhr.send(loginMsg);

	var loginJson;
	if(xhr.status == 200) {
		loginJson = JSON.parse(xhr.response);
	} else {
		RTA.displayResponse("Failure", "Problem logging into flood. HTTP code " + xhr.status + " " + xhr.statusText + "\nContent:" + xhr.responseText, true);
		return;
	}
	
	if(torrentdata.substring(0,7) == "magnet:") {
		var mxhr = new XMLHttpRequest();
		mxhr.open("POST", scheme + server.host + ":" + server.port + "/flood/api/client/add", true);
		mxhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8");
		mxhr.onreadystatechange = flood_handleResponse;
		var message = JSON.stringify({ "urls": [ torrentdata ], "start": !paused, "destination": (!!dir ? dir: undefined) });
		mxhr.send(message);
	} else {
		var xhr = new XMLHttpRequest();
		xhr.open("POST", scheme + server.host + ":" + server.port + "/flood/api/client/add-files", true);
```

**Comment by bogenpirat** [comment]
from what i can tell, the code still works fine. just tested it with the latest commit over at https://github.com/Flood-UI/flood/commit/bb553506a86225811a965563af99bf8e39cc433f.

you wouldn't happen to have set a custom `baseURI` in config.js? if so, would you mind trying it with the standard value of `'/'`?

if this works fine and you've done this intentionally, let me know. adding custom api paths for reverse proxy support for every client isn't particularly high on the list of priorities right now though.
