### ISSUE TITLE
Notification option not working with Microsoft edge

### ISSUE THREAD

**Issue by bclinton1** [bogenpirat/remote-torrent-adder#277]
Installed the latest version - Version 83.0.478.61 (Official build) (64-bit)

Receive no notification when torrent added. The torrent adds to the transmission client but no notification.

**Comment by bogenpirat** [comment]
please give this test build a try: https://github.com/bogenpirat/remote-torrent-adder/issues/262#issuecomment-667723767
let me know if that works; it did for me.

**Comment by ktdd** [comment]
Yeah, that works. I got updated to 1.3.0 yesterday and I couldn't upload torrents anymore. This build works and gives a notification.

**Comment by zeroalias74** [comment]
this version referenced is working perfectly as the user above stated, no issues on Edge or Chrome
