### ISSUE TITLE
Torrents not being added to ruTorrent

### ISSUE THREAD

**Issue by ajtatum** [bogenpirat/remote-torrent-adder#278]
I'm honestly not sure if this is strictly related to ruTorrent as it's the only client I have. However, it was working the other day and I noticed it was just upgraded to 1.3.0. Not sure of what changes were made, but basically using Chrome 84.0.4147.105 on Windows 10... I click on a torrent/magnet link the window pops up (I have label interactivity turned on) and I select a label and click submit and nothing happens. No notification, nothing appears in the torrent downloader... no console errors reported to the browser. It just silently fails. I haven't tried it on other browsers because or tried to downgrade the plugin because, quite frankly, I don't want to go through the setup again LOL. But if I have to, I will. Please let me know...

Thanks,
AJ

**Comment by ajtatum** [comment]
Ok, so I noticed you added a nifty export/import feature so I tried it in Edge 84.0.522.52 and it works perfectly. So, it seems to be a Chrome issue.

**Comment by winedog** [comment]
It looks like the new update allows Magnet links to be caught, but the previous behavior where Remote Torrent adder could intercept .torrent files in Chrome via the right-click menu is now broken?

**Comment by winedog** [comment]
Just tested using latest Edge and it seems intercepting of .torrent files works there, but not in Chrome?

**Comment by ajtatum** [comment]
Yea, in the latest version of Edge the extension works perfectly. However, in Chrome, when I click on the link to download a file the Remote Torrent Adder window pops up but once I click submit, nothing happens. Whereas in Edge, I immediately get a notification that ruTorrent received my request.

**Comment by bogenpirat** [comment]
naturally, it works fine for my setup(s) (or else i wouldn't have released it).

just to summarize:
- the issue occurs only in chrome
- ruTorrent client

@ajtatum does it make a difference whether you have label/dir chooser modal enabled or not?

if the developer console (F12) doesn't show anything on the site itself (which would imply that the content script worked), does it show something for the background page? you can reach it via `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci`, enabling developer mode in the top right and then under inspect views clicking on "background page". if there was an internal error, this console should display it as you try adding a torrent.

**Comment by RichardBarrett** [comment]
I am experiencing the very same issue. Background page error:

`
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.RTA.clients.ruTorrentAdder (ruTorrentWebUI.js:8)
    at Object.RTA.dispatchTorrent (functions.js:24)
    at XMLHttpRequest.xhr.onreadystatechange (functions.js:74)
`

**Comment by bogenpirat** [comment]
ah. thanks for that, please have a go at this version: 
[remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/5021748/remote-torrent-adder.git.zip). instructions over at https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code

though i'm a bit confused - if this is the root of OP's problem, it shouldn't have worked with exported settings in another browser either, and according to https://github.com/bogenpirat/remote-torrent-adder/issues/278#issuecomment-668400686 it did.

so if this build doesn't work for @ajtatum and @winedog, you two should take a look at the background page as well and let me know if there's something else there.

**Comment by heinowalther** [comment]
Tried with the git.zip version... same thing.. Chrome on MacOS... also cannot get it to work on Edge either... no matter platform.. (Windoze or MacOS)...

Here are the errors I get in the devtools console...

VM81:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.RTA.clients.ruTorrentAdder (ruTorrentWebUI.js:8)
    at Object.RTA.dispatchTorrent (functions.js:24)
    at XMLHttpRequest.xhr.onreadystatechange (functions.js:74)
RTA.clients.ruTorrentAdder @ ruTorrentWebUI.js:8
RTA.dispatchTorrent @ functions.js:24
xhr.onreadystatechange @ functions.js:74
XMLHttpRequest.send (async)
RTA.getTorrent @ functions.js:81
(anonymous) @ background.js:76

**Comment by bogenpirat** [comment]
i had to update the code from this post a few minutes ago. sorry for the hoops, but would you mind re-downloading and trying again?

**Comment by heinowalther** [comment]
:-)  The new version seem to solve the issue... thanks!  When will this be in he "Chrome-Shop"?

**Comment by bogenpirat** [comment]
right now, this looks like it stems from an oversight on my end with a new feature that i wrote a long while ago, but never released, and old (pre-1.3.0) configurations of RTA. it definitely will land in a bugfix release, but i'd first like to hear from the other commenters whether this was indeed related to the original issue.

**Comment by RichardBarrett** [comment]
@bogenpirat Worked like a charm. Thanks.

**Comment by winedog** [comment]
Strangely - I managed to get 1.30 working.  Not sure exactly how I did it, but I thought maybe it was a problem with Chrome's protocol handler and I tried to reset that (which is actually not easy in the latest Chrome since they removed those settings).   I essentially completely reset the site permissions in Chrome for the domain I access rutorrent on and then also reset site permissions on two of the sites I primarily grab torrents from.  After fully dumping the cookies and clearing all the permissions, it started working for me?  I've also tested your update version @bogenpirat and it works, but no different than it does after I managed to get 1.30 working for myself?

To be clear my issue at the beginning was:

- Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- rutorrent
- Magnet links worked, but .torrent files didn't

**Comment by bogenpirat** [comment]
@winedog well, the issue described by the symptoms in https://github.com/bogenpirat/remote-torrent-adder/issues/278#issuecomment-668530975 stems from https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js#L8 (and line 31).

`autolabellist` and `autodirlist` are not present in the configurations of people who last changed their settings before 1.3.0 - thus the ruTorrent code specifically fails. if you've changed any of your settings since this became an issue after 1.3.0, these variables are filled (albeit empty) and will not prevent proper code execution. i assume that's it?

**Comment by winedog** [comment]
@bogenpirat - ah I suppose that could be it.  I think I nuked all my settings for remote torrent adder as well when I tried resetting everything.  I manually reconfigured rutorrent instead of using the export/import function.

**Comment by l4rryGitgend** [comment]
Thanks for the help. 
I reinstalled the Chrome Extension in Chrome and did my rutorrent settings from scratch, now it works again.

**Comment by aaronstc1** [comment]
Not sure if this is helpful at all but mine started working again and I did nothing. Is there some kind of service that could have been down?

**Comment by bogenpirat** [comment]
pushed it to the web store in 1.3.1, expect it to land in your chrome within the next few days.

**Comment by ajtatum** [comment]
So, I uninstalled the extension from Chrome and reinstalled it... then imported my settings. It works now! Yay!
