### ISSUE TITLE
Feature Request: Support for UTF-8 in label/directory selection.

### ISSUE THREAD

**Issue by victordk** [bogenpirat/remote-torrent-adder#280]
As it is right now - RTA does not support æøå as chars - it translates those to question marks.
Hope it can be implemented somehow.
Cheers.

**Comment by bogenpirat** [comment]
okay, some more information would be neat. which client are you using? i just tried ruTorrent and aside from a related bug, it seems to work: labels are submitted correctly and with a minor fix, a custom directory was created and downloaded to correctly as well. no question marks - without the fix it just downloaded to the default directory.

charset issues might stem from the encoding of the source/destination (torrent client) website. please go to the website you're trying to download from and hit F12 to open the developer console, then type `document.characterSet` there and write that down somewhere. repeat the same for your torrent client's web ui and let me know whether those are different from `UTF-8`. and if so, ideally let me know the respective values so i can try to reproduce this issue.

**Comment by victordk** [comment]
Oh iam sorry - Qbittorrent 4.2.5 running on Windows 10 Pro. Browser: Chrome  84.0.4147.105

**Comment by victordk** [comment]
The torrent site and qbittorrent webui reports UTF-8 when i do the document.characterSet i developer console.

**Comment by bogenpirat** [comment]
i think this fixes it, please give it a try and let me know: [remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/5031303/remote-torrent-adder.git.zip)

instructions: https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code

**Comment by victordk** [comment]
That fixed it straight away - very much appreciated - thx.
Hope you can merge the fix soon :)

**Comment by bogenpirat** [comment]
thank you. i'll try to toss this one into the shop within the next few days, depending on some other issues.
