### ISSUE TITLE
Torrent adder stopped working with rutorrent 0.9.7/0.13.7

### ISSUE THREAD

**Issue by davidms12** [bogenpirat/remote-torrent-adder#281]
It's been working fine for years. Yesterday and today trying to add torrents it immediately logs me out of my UI for rutorrent. Haven't changed any settings. Verified passwords are correct. What should I be looking at to try and resolve this?

thx

**Comment by bogenpirat** [comment]
does the web server you run rutorrent on use digest authentication? if possible, switch to http basic auth.

**Comment by davidms12** [comment]
Hi Julian. I'm not sure if it's using digest authentication. It passes username with no hash so does that indicate basic auth? I've also noticed that testing torrent adder with 'hit me' no longer produces a pop-up dialog. I have removed the extension and re-added to attempt to fix but this hasn't worked. my rutorrent host is dediseedbox.com if that helps.

thx

**Comment by bogenpirat** [comment]
i've no experience with that provider (or any).

go to your web ui, hit F12, then go to the network tab, then hit F5 to reload the page. the first request (click it) should contain a request header `Authorization`; its content could be something like `Basic xyz` or `Digest xyz`.

**Comment by davidms12** [comment]
you are correct Authorization is Digest. Do you know how I may change that in rutorrent? I don't see anything in settings. I suspect the provider will not change it for me...

**Comment by bogenpirat** [comment]
you can't change that in rutorrent. if you have access to the rutorrent folder, there's a chance you can edit its .htaccess file. there's unfortunately an even better chance that it won't work this way because your provider configures users elsewhere centrally and you can't override it, even if you have access.

your best bet is to ask your provider whether they have an option to switch authentication modes. sorry about that.

**Comment by bogenpirat** [comment]
alright, hang on.

**Comment by bogenpirat** [comment]
@davidms12 mind checking if this works for you? [remote-torrent-adder.git.zip](https://github.com/bogenpirat/remote-torrent-adder/files/5070473/remote-torrent-adder.git.zip) instructions on how to set it up: https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code
feel free to backup settings from the chrome web store version of the extension and restore them into the unpacked version here.

**Comment by davidms12** [comment]
Hi Julian. I gave it a go. Here is the error it throws.
![error](https://user-images.githubusercontent.com/62469147/90174601-7d2fb200-dd63-11ea-8141-aa60ee849725.jpg)

**Comment by bogenpirat** [comment]
thanks for giving it a go.

that error stems from not reloading the page you're trying to add torrents from *after* adding the extension. please make sure to take these steps:
1. disable the RTA version from the chrome web store in `chrome://extensions/`
2. dis- and enable the RTA version from disk (it has an orange icon next to the RTA icon)
3. reload the page with a torrent on it and try adding it the way you normally would.

thanks!

**Comment by davidms12** [comment]
Ok so I've uninstalled the extension again. So no extension in chrome. Then I Loaded unpacked extension and configured it from scratch (I did not import settings). I logged out of my torrent site and logged back in and I also logged out of my seedbox and logged back in. Then I tried a torrent  - I get the same Uncaught error: Exxtension context invalidated.

**Comment by bogenpirat** [comment]
okay, that's thorough. thanks for establishing a clean protocol. naturally, you shouldn't be receiving this error if you're proceeding the way that you're describing it.

that being said, i went through the steps you've outlined and it works just fine for me - no errors. for reference, that's what my test settings look like: 
![image](https://user-images.githubusercontent.com/1835496/90183488-dd4e4480-ddb3-11ea-885d-2945497c7d50.png)

have you checked whether you're seeing the same symptoms on any site with a torrent link? try https://webtorrent.io/free-torrents for example

**Comment by davidms12** [comment]
Just added in relative path /rutorrent and it works! Strange because I had tried the relative path in the extension from chrome but it didn't work. Seems to be working now :) thanks for your dedication to the plugin! I'm a happy man again.

And yes, I had been using it with rarbr and it works there - just wouldn't work with scenetime. Strange.

**Comment by bogenpirat** [comment]
alright, so just a misconfiguration. good to hear that the digest code works. i'd like to hear back from the gent over at #283 whom i sent here, then it'll probably land in 1.3.3.

**Comment by fredtjd** [comment]
This works for me when previously I was getting the errors discussed elsewhere. Thanks for your hard work.

**Comment by davidms12** [comment]
So happy this extension is working again. Makes managing torrents so much easier. Thanks again for your efforts!
