### ISSUE TITLE
Qtorrent: label and category collection & use of; Dir not working it seems

### ISSUE THREAD

**Issue by yeders** [bogenpirat/remote-torrent-adder#284]
Hi team,

I can add torrents via RTA (this program - CHROME Extension), but the Label/Directory list doesn't contain the labels/categories (which are dirs by config) set up within QTorrent. 

Is it meant to be there?
If not, then when I create a new directory from the RTA prompt, the dir isn't applied to the item downloaded and just downloads to the default dir.

Thanks

**Comment by bogenpirat** [comment]
The labels you currently have in your web ui are **not** supposed to show up (or sync) with RTA. RTA keeps its own list.

As for the failing folder creation: i tested this a short while ago on my test setup and it seemed to work fine. If you try adding a torrent manually via the web ui in the browser, does it work there? 
If not, this may indicate an issue with your setup of qbt (permissions, etc.). If it does work there, please let me know and I'll try to investigate.
