### ISSUE TITLE
Getting Error Could not download torrent file

### ISSUE THREAD

**Issue by whiteshadow01** [bogenpirat/remote-torrent-adder#291]
I am currently not able to download torrents as I am getting this error.

Failure Could not download torrent file
ERROR: Maximum call stack size exceeded.

**Comment by FreddyFred666** [comment]
I have the same problem since yesterday ... anyone has a solution ? Please.

**Comment by bogenpirat** [comment]
#290 and 1.3.5 fix this problem. I submitted the new version yesterday, seems like it's not yet in the store. Gotta be patient now. If 1.3.5 doesn't fix it for you, please come back and let me know.

**Comment by FreddyFred666** [comment]
Thanks! The problem has been solved itself, strange....
