### ISSUE TITLE
Server settings keep disappearing

### ISSUE THREAD

**Issue by OrangeLore** [bogenpirat/remote-torrent-adder#292]
This past week I have had to add my server back into the settings 3 times. I don't know if there was an update or not but with over a year of using this extension this is my first time having a problem.

**Comment by bogenpirat** [comment]
alright, a gentlemen mentioned something like this a while ago, guess i can take it serious now despite never experiencing it myself.

unfortunately, i'm not sure where to begin... what do your settings look like? e.g.: what client? do you use the label/dir interactivity? anything special you did prior to the loss of data? what browser?

**Comment by OrangeLore** [comment]
I use Chrome for my browser. Nothing has changed. My computer never turns
off and only resets during MS updates. All settings are normal to what is
set when installed. I have attached some pictures to help. I also do not
know what has caused this, or where to start. Like I said I have been using
this extension without any issue until now.

If you need anything else from me please let me know. Also I don't know if
possible but could there be a way to just save config to computer and
restore if needed?

This is not a huge issue as it does not take me long to put in my settings,
just wanted to report it so you can be aware.

**Comment by OrangeLore** [comment]
[Extensions](https://ibb.co/GnQ07tr)
[Remote Torrent Adder Options](https://ibb.co/StNN1Yc)
[Remote Torrent Adder](https://ibb.co/BCmdpcV)

**Comment by bogenpirat** [comment]
Doesn't look like anything's out of the ordinary here. In fact, that's an exceedingly simple config. 
Can you tell whether the wipe, for lack of a better term, occurred *between* browser sessions, or *during* one of them? Meaning, might it have happened during a reboot/time when all browser windows were closed?

You can easily import/export settings in the import/export settings tab in the rta options.

**Comment by OrangeLore** [comment]
I tend to leave my browser open for weeks at a time, usually windows update closes it all. I have tried rebooting multiple times past few days  with no change. Also since the 3 times the settings have disappeared last week I have had no issues. Again nothing has changed. I run Zone Alarm, Avast and Malwarebytes at all times with chrome.

**Comment by GarethWright** [comment]
I have this all the time.
The only thing I can think of is something like MalwareBytes or CCleaner deleting the local storage.
Regardless, it should be simple to persist the settings with the Google Sync

**Comment by bogenpirat** [comment]
> I have this all the time.

that sounds really annoying.
> The only thing I can think of is something like MalwareBytes or CCleaner deleting the local storage.

that would be really fucking stupid and a really undesirable effect on my computer's software if i were a user of those programs.
> Regardless, it should be simple to persist the settings with the Google Sync

probably easy enough, yes. it's unfortunately a feature that would actually annoy/be problematic for me personally, so i'm not too interested in implementing it.

in any case, it seems more prudent to fix the issue at its root cause instead of trying to fix the symptom.

that being said, if anyone can point me to a way of reproducing the issue, please post here. in the meantime, i'm going to assume that this is caused by external factors and not due to an RTA bug.
