### ISSUE TITLE
brave browser: can't get directories working with rutorrent WebUI (permissions?)

### ISSUE THREAD

**Issue by haggletonpie** [bogenpirat/remote-torrent-adder#296]
RTA is works very well, except that i can't seem to get the directory feature to kick in.

Perhaps related, Brave says that RTA 'can't read or change' data on any website, even though those permissions are asked for and granted on (repeated) installs.

I'm using Xirvik to get by for now. It's kind of icky, but is able to converse with rutorrent about directories, and present a chooser box.

Looking for any suggestions on how to diagnose this. Thx.

**Comment by bogenpirat** [comment]
there are actually two separate ways of using directories: one (1) where you just let RTA send all the torrents you add to one particular directory (or label), and one (2) where you interactively set it with a modal dialog.

does (1) work? does adding torrents work at all?

in order for the modal to show up, RTA needs to be permitted to inject [two scripts](https://github.com/bogenpirat/remote-torrent-adder/blob/master/manifest.json#L46) into the website's content. the first one, `content_rta.js`, makes catching/adding links possible in the first place. the second one, `modal.js`, contains the code for displaying and running the modal overlay window.

> that RTA 'can't read or change' data on any website

where does it say that? this does not happen on my install of brave. have you made any strict settings in brave itself?

finally, does it *not* work on any page with torrent links, or just one in particular?
