### ISSUE TITLE
When adding to rutorrent am told it can't connect to server but torrent is still added

### ISSUE THREAD

**Issue by Fogest** [bogenpirat/remote-torrent-adder#297]
Everytime I submit a torrent via magnet or torrent file using the remote torrent adder it tells me it can't contact my server and says "Error: Not Found" however it actually did work and the torrent does in fact get added to my rutorrent, correct label and directory and everything. 

![image](https://user-images.githubusercontent.com/1163628/98030529-27f1c280-1ddf-11eb-9e97-93e34ae0ed91.png)

**Comment by bogenpirat** [comment]
sounds like #295. do you use a non-standard ruTorrent install?

**Comment by Fogest** [comment]
Haha, yes in fact I am also using swizzin.
