### ISSUE TITLE
directories not working with qbittorrent

### ISSUE THREAD

**Issue by guliciuc** [bogenpirat/remote-torrent-adder#299]
Hi
Seems that the directories dropdown for qBittorrent v4.3.0.1 Web UI (64-bit) will not populate, and if a directory name is to be entered manually, it will not populate the directory list in qBittorrent.
Any ideeas?
Best regards

**Comment by bogenpirat** [comment]
label/directory management in RTA seems to work with no problem in my tests here. perhaps i misunderstand what exactly you mean?

my steps:

1. enable label/dir interactivity in options
2. click a link on a website
3. be presented with the label/dir chooser modal
4. add the torrent
5. the torrent gets added properly to qbt v4.3.0.1 with label/dir as requested
6. click another link
7. be presented with the label/dir chooser modal with now filled-in label/dir pair from before

what did you try/expect?

**Comment by guliciuc** [comment]
Hello

Sorry, i believe i misunderstood the functionality. I was expecting to have
a dropdown with all the categories or the paths set in them in qbittorrent.
So i would not need to assign them manually in a category afterwards from
the webUI. Would be a useful function, just to have a listing of the
categories, .

Thanks for your time
Best regards
