### ISSUE TITLE
Flood Project Dead  >  Fix / New Server Type: Flood  (New Highly-Active Fork)

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [bogenpirat/remote-torrent-adder#300]
The awesome Flood can now be considered abandoned :(  It's last release was over a year ago (in fact; no commits at all), & unfortunately its author has become unresponsive for a long time.

Fortunately it has been [forked](https://github.com/jesec/flood) and development resumed [in-force](https://github.com/jesec/flood/blob/master/CHANGELOG.md) - this fork can now be considered the official Flood going forward, with very active development & a serious roadmap.  It now has a proper thought-out API, along with a test suite :D

<br/>

Some details / a comparison;

Old Flood (abandoned)
-  Github  >  Flood-UI/flood: A web UI for rTorrent with a Node.js backend and React frontend.  [[https://github.com/Flood-UI/flood](https://github.com/Flood-UI/flood)]
-  <1400 commits
-  No commits for 1Y  >  Commits · Flood-UI/flood  [[https://github.com/Flood-UI/flood/commits/master](https://github.com/Flood-UI/flood/commits/master)]
-  Old changlog (too much hoped, longstanding stale todo)  >  flood/CHANGELOG.md at master · Flood-UI/flood  [[https://github.com/Flood-UI/flood/blob/master/CHANGELOG.md](https://github.com/Flood-UI/flood/blob/master/CHANGELOG.md)]
-  Project quality not up to standard  >  [Discussion] Project quality · Issue #712 · Flood-UI/flood  [https://github.com/Flood-UI/flood/issues/712]
-  no active dev warning · Pull Request #774 · Flood-UI/flood  [[https://github.com/Flood-UI/flood/pull/774](https://github.com/Flood-UI/flood/pull/774)]
-  Status on project? · Issue #877 · Flood-UI/flood  [[https://github.com/Flood-UI/flood/issues/877](https://github.com/Flood-UI/flood/issues/877)]

New Flood (jesec fork)
-  Github  >  jesec/flood: A modern web UI for various torrent clients with a Node.js backend and React frontend.  [[https://github.com/jesec/flood](https://github.com/jesec/flood)]
-  ~2000 commits (~600 in the past few months!)
-  Daily commits!  >  Commits · jesec/flood  [[https://github.com/jesec/flood/commits/master](https://github.com/jesec/flood/commits/master)]
-  Solid progression  >  flood/CHANGELOG.md at master · jesec/flood  [[https://github.com/jesec/flood/blob/master/CHANGELOG.md](https://github.com/jesec/flood/blob/master/CHANGELOG.md)]

<br/>

However; the move to a proper API has broken compatibility with the (new) Flood integration in RTA.  
(I can confirm the old Flood still works with RTA).

The error in the pop-up is;  
> "Failure
> Could not contact <my chosen name for Flood server>
> Error: Not Found"

<br/>

I've tried taking a stab at it, but not had much luck.  Here are some files I've been looking at; 

It seems the OLD api was here:
-  [flood/server/routes/api.js
](https://github.com/Flood-UI/flood/blob/master/server/routes/api.js)

This is the relevant NEW api:
-  [flood/server/routes/api/torrents.ts](https://github.com/jesec/flood/blob/master/server/routes/api/torrents.ts)

This now has test cases which show / demonstrate the new api usage;
-  [flood/server/routes/api/torrents.test.ts](https://github.com/jesec/flood/blob/master/server/routes/api/torrents.test.ts)

Old endpoint  =  `/api/client/add`
New endpoint  =  `/api/torrents/add-urls`

<br/>

I'd vote for RTA's Flood config to be updated to the new version (jesec's), & dropping the old Flood support entirely.  

Alternatively; we could move the old Flood support to: "Flood (legacy)" for X months to give people awareness & a smoother migration path - before stripping it entirely? 

O_O

**Comment by bogenpirat** [comment]
thank you for the detailed report. i'll implement support for this.

i disagree about dropping support for the old flood however - people never update their setups and just yanking the rug from under their feet by dropping support for software they're still productively using seems stupid. so i'll probably create a new client and name it something like "Flood (jesec fork)".

it may be a while before i start work on this though, my testing environment for torrent clients is broken right now.

**Comment by bogenpirat** [comment]
alright, that was relatively painless.

couple of notes:
- same feature set as the original flood client (paused, default directory)
- flood will accept just about anything as a "torrent" file. send it HTML and it'll accept it. so the success notification is somewhat useless. the failure notification will only ever show up if the server isn't reachable; not if the torrent file sent is garbage.

**Comment by KangarooCreativeTeam** [comment]
Yay!  

Thanks for implementing support for that.

I've tested that commit - I can confirm it's working perfectly with Jesec's Flood. 

Thank you :D

_____

You are right - we shouldn't remove the old Flood support just yet.  That was a premature notion on my part.

Of interest; the old Flood's author (John Furrow (jfurrow)) has [at last acknowledged](https://github.com/Flood-UI/flood/issues/889#issuecomment-743471799) Jesec's new fork, & by extension (& going by his choice of words), I believe has acknowledged that his project isn't progressing.  A shame - he created a great project.  Hopefully he'll come back into the fork one day :) 

Point being; it was a good move to add support for the new fork in RTA.

Thank you Julian :D

**Comment by bogenpirat** [comment]
> choice of words

that's an overly enthusiastic use of a plural if i've ever seen one ;)

somewhat relevant side note: this project and i myself have been subject to some criticism for similar inactivity. just go take a look at the spacing of commits of and before v1.3.0. nobody else seemed to pick up the mantle and create a fork, so i eventually went back to keep working on RTA. i can't say how i would've felt if somebody else had taken over the project, even though it might've been deserved at that point. kinda always had the intention of putting more work into RTA, just never found the time until i finally did. what i'm trying to say is: don't be too eager to discount jfurrow's repository/upstream work. things may change. i'm sure he's laid a good foundation for jesec's indubitably terrific work.

in any case: a separate client handler is the correct choice for whatever happens in future. if jesec f.e. ever chooses to rename their fork, changing/adding a label to RTA for the new API is trivial.

thanks for checking the code out, i'll get it released in a bit.
