### ISSUE TITLE
Sidekick Browser - Not working at all / Test notification not working either

### ISSUE THREAD

**Issue by gaa23** [bogenpirat/remote-torrent-adder#301]
The title says it all. Not sure how to troubleshoot. Works fine on Chrome.

**Comment by bogenpirat** [comment]
seems to work fine for me on a fresh install - i added a torrent to a qbt client just fine.

are there any error messages when you go to `chrome://extensions/`, enable developer mode and click on inspect views **background page**?

**Comment by gaa23** [comment]
It says there is a 405 error (Not allowed).

**Comment by bogenpirat** [comment]
alright, that's pretty weird. using the same devtools as in https://github.com/bogenpirat/remote-torrent-adder/issues/301#issuecomment-768385548 and after clicking on the network tab, then when you add a torrent file (and it fails), click on the request  in the upper pane and let me know what it says under "request method"?

does the "response" tab in that view give any more detail on what exactly it doesn't like?

**Comment by gaa23** [comment]
Its working now, I think I used the wrong server type which didn't allow me to configure the relative path. Thank you for the support.
