### ISSUE TITLE
qBittorrent HTTP Error Code 404

### ISSUE THREAD

**Issue by Brodieman** [bogenpirat/remote-torrent-adder#302]
I see several references to this but could not make sense of the responses.  I have qBittorrent running on a NAS and connect with the WebUI.  I am looking for an extension that adds magnets and links to it, this says it does that.  However when I try I get "Server responded with an irregular HTTP error code 404".  I am using Chromium Edge.  qBittorrent version is 4.1.7.  Thanks for any help!

**Comment by bogenpirat** [comment]
seems to work fine for me. can you check that you when adding a server, you chose "qBittorrent v4.1+ WebUI" and not the one that lacks the version number in its name?

**Comment by Brodieman** [comment]
You know what, I never "added" a server I just edited the default one.  Works now, sorry!
