### ISSUE TITLE
Using remote Torrent adder on a deluge style and I seem to have stopped notifications

### ISSUE THREAD

**Issue by Hawkeye56** [bogenpirat/remote-torrent-adder#305]
How do I restart these?

**Comment by bogenpirat** [comment]
you can get into the extension's settings by typing `chrome-extension://oabphaconndgibllomdcjbfdghcmenci/options.html` into your address bar in chrome. there's a notifications tab that lets you dis- and enable them.

if that's not the issue, notifications are probably being suppressed by chrome or the OS.
PS: i used to have spotty results with notifications until i did some research and found out that windows 10 limits notification display when some application is in full screen mode.

**Comment by Hawkeye56** [comment]
Turned out to be Windows notifications, which in the new update seem to be
more strictly adhered to then previously.  I had seen the notifications tab
but the test button didn't work.  Funnily when I switched on audible
notification I heard the ping but still no pop-up, so went to windows and
got it working.  Thanks for the help.
