### ISSUE TITLE
R-T-A Broke?

### ISSUE THREAD

**Issue by waffi121** [bogenpirat/remote-torrent-adder#308]
Hello Together

Unfortunately I can not open the addon anymore, it always comes: 

The website is not reachable
127.0.0.1 has refused the connection.

I have now completely uninstalled Chrome, reinstalled and installed only the addon. Is it because of the Chrome update? I also tested it on a Mac and Windows. 

Thanks for the help!

**Comment by bogenpirat** [comment]
you might want to check whether your web ui is accessible at all. ideally, check that:

1. the webui is enabled in your torrent client
10. you can access it over the browser
100. there are no firewalls running that forbid you from accessing your loopback device (127.0.0.1)

if any of these are the case/fail, it's not RTA's fault.

**Comment by waffi121** [comment]
sorry for your time. with a friend on the pc it also runs. funny I can not find the error unfortunately. but have found an alternative:) 

have a good time
