### ISSUE TITLE
Can't connect after chrome crash

### ISSUE THREAD

**Issue by cgolchert** [bogenpirat/remote-torrent-adder#310]
I had an instance of Chrome just cease to be running.  After re-launching it and telling it to restore open tabs this extension had the settings wiped out.  When I try to add a link now it IMMEDIATELY fires back a notification telling me:

Failure
Could not contact [server]
Error: Not Allowed

It happens so fast it looks like it isn't even trying to send anything to the network.

Trying to set it up for ruTorrent v3.9.  It was working fine before the instance of chrome crashed.

**Comment by bogenpirat** [comment]
have you tried re-doing your settings then? sounds like a systemic problem more so than a bug with this extension.

**Comment by cgolchert** [comment]
I've reentered the settings.  The other chrome extensions didn't drop settings.  If I click on the icon it takes me to the rutorrent webUI page and that loads correctly.  If I try to get RTA to intercept any torrents it Immediately gives me errors.

**Comment by cgolchert** [comment]
The seedbox company happened to change things the same time as the crash.  Got it sorted.  Closing this out.  Thanks for the quick reply.
