### ISSUE TITLE
Remote Torrent Adder stopped working - could not contact Seedbox

### ISSUE THREAD

**Issue by MohnJadden** [bogenpirat/remote-torrent-adder#312]
I've had Remote Torrent Adder working without issues for a year or so on Chrome, sending to my Deluge seedbox.  All of a sudden, it stopped working.  My seedbox IP hasn't changed, nor have my credentials, etc.  Whenever I right click a torrent to send to the remote webUI, I get an error notification: "Could not contact Seedbox, error: cannot read properties of null (reading 'message')."  I've been using default link catching without incident.

I restarted the Deluge service on my seedbox, issue persisted.  Tried with both the daemon port instead of webUI as normal, issue persisted.  I deleted and re-created the server in the WebUI tab, issue persisted.

**Comment by bogenpirat** [comment]
aight, good effort eliminating some of the variables!

1. what version of deluge?
2. go to `chrome://extensions/?id=oabphaconndgibllomdcjbfdghcmenci`, enable `developer mode` in the top right, then go to `inspect views` -> `background page`. go to the `network` tab, then hit `F5`. then try to add a torrent like you would usually, provoking the error. any error logs (red) produced there?

**Comment by TheFluffis** [comment]
I also noticed Remote Torrent adder stopped working a few weeks ago. I'm using qBittorrent v4.4.0rc1. I tried @bogenpirat suggestion with developer mode. Either I'm doing it wrong otherwise there ain't no network traffic going at all. I've also tried different ports in the add-on web ui to rule that out
Attached a print screen showing the error message.

![asd](https://user-images.githubusercontent.com/93650730/141316935-83e145d4-a80b-4c22-a176-43298dbfb829.jpg)

**Comment by bogenpirat** [comment]
> Either I'm doing it wrong otherwise there ain't no network traffic going at all.
pretty sure you're doing something wrong, there should definitely be requests there if you do everything in the order that the post says. 

the error message implies that fetching the torrent already fails. have you tried another source for torrent links than the one that is failing? e.g. https://webtorrent.io/free-torrents

**Comment by TheFluffis** [comment]
I don't know what the problem was but in remote torrent adder I removed my server and added it again and it started working. Thanks!

**Comment by xxtensazenxx** [comment]
Having this same issue "Failed to fetch"

**Comment by superpupervlad** [comment]
Had the same issue, reinstalling the extension somehow helped
