### ISSUE TITLE
Cannot add torrents when Referrer String is required

### ISSUE THREAD

**Issue by eos1d3** [bogenpirat/remote-torrent-adder#314]
Some web sites do not use cookies, but using Referrer String to prevent link sharing. Current version cannot download torrents and send to qBittorrent with this restriction.

But I find Aria2 for Chrome can send these torrents to Aria2. So it should be possible to fix this issue.

**Comment by bogenpirat** [comment]
> Some web sites do not use cookies, but using Referrer String to prevent link sharing. 

seems stupid, but alright.

please try out [this](https://github.com/bogenpirat/remote-torrent-adder/archive/refs/heads/issue-314.zip) using [these](https://github.com/bogenpirat/remote-torrent-adder/wiki/Try-new-code) instructions.

**Comment by bogenpirat** [comment]
an oversight made the above code useless; it's fixed now. please try again using the updated zip archive from the same link. after overwriting the folder, you'll need to reload the extension (`chrome://extensions/` has a refresh button next to it) as well as F5 the tab you're getting the torrents from.

**Comment by eos1d3** [comment]
Hi, this works perfectly now for both with or without Referrer string requirement.

Actually this is not stupid as Aria2 extension does similar thing. 😅

Thank you!

**Comment by bogenpirat** [comment]
great, i'll merge and push this to the web store. might take a day or so to update, as usual.

> Actually this is not stupid as Aria2 extension does similar thing. 😅

yeah, obviously the solution is fine. :) but relying on the referer field for authentication is stupid.
