### ISSUE TITLE
Feature request: multiple context menu entries

### ISSUE THREAD

**Issue by hojnikb** [bogenpirat/remote-torrent-adder#322]
Maybe a dumb request, but would it be possible to add multiple menu entries on the context menu for each server? 

Instead of just one "Add to remote WebUI" maybe something like "Add to _server name_" and bellow it "Add to _server name2_" and so on. Would make adding multiple torrent a tiny bit more convenient and faster.

Thank you!

**Comment by bogenpirat** [comment]
well, seems you're in luck. add a second server and see how the context menu behaves!

**Comment by hojnikb** [comment]
> well, seems you're in luck. add a second server and see how the context menu behaves!

That's what i want to change. I'd like to have multiple context menu entries on the main right click menu. Now you have to click on the webui entry, slide over and select your server.  It's a little thing, but would go a long way :)

**Comment by hojnikb** [comment]
I've made a mockup of what i was thinking.
![Brez naslova](https://user-images.githubusercontent.com/2211467/150697134-f7128c58-2a19-4371-a6f0-cde23e53b2dd.png)
.

**Comment by bogenpirat** [comment]
as per [this](https://developer.chrome.com/docs/extensions/reference/contextMenus/#usage):
> You can create as many context menu items as you need, but if more than one from your extension is visible at once, Google Chrome automatically collapses them into a single parent menu.

your request cannot be implemented. even if it was possible, i think out of personal preference, i would probably not have gone along with it. sorry.

**Comment by hojnikb** [comment]
> 

that makes sense. Thank you!
