### ISSUE TITLE
visual notification banners no longer working in chrome

### ISSUE THREAD

**Issue by mcandre** [bogenpirat/remote-torrent-adder#323]
Hi,

The audible notification chime works in Chrome, but the visual banners no longer display.

Latest stable Chrome, macOS.

**Comment by bogenpirat** [comment]
unfortunately, i have no mac hardware to test this on. windows f.e. has a policy where it will not display notifications if there is any window in maximized state - be it browser or anything else. could this be the case for macos as well?

**Comment by newadventure079** [comment]
I remember someone saying there was a bug in macOS regarding this

**Comment by newadventure079** [comment]
FWIW, Brave got them to work.  https://github.com/brave/brave-browser/issues/13771

I downloaded Brave and verified they work from the testing sites and from RTA

**Comment by bogenpirat** [comment]
thanks for the input. sounds like this needs to be resolved upstream in chrome/macos. closing this issue in the meantime, let me know if it needs to be reopened.

**Comment by byrondover** [comment]
I'm experience the same issue with this extension, Chrome on macOS.
