### ISSUE TITLE
Dialog appearing behind page content

### ISSUE THREAD

**Issue by BryanWall** [bogenpirat/remote-torrent-adder#325]
Left clicking on magnet links on this site causes the RTA dialog to appear behind the page content, presumably because they are using z-index:9999 vs your dialog z-index:1000. Right clicking the link and choosing Add to remote WebUI, however, causes the dialog to appear on top. 

http://mgnet.me/eqxC5pZ

Do you know if there's a way to make the main dialog appear on top of the other content, without just brute forcing it with z-index:9999999? 

What causes the right click dialog to be on top? Is that something about how Chrome extensions handle right click contexts menus or is there something different about the styles on that version of the dialog? I looked at the styles briefly and didn't see anything obvious.

**Comment by bogenpirat** [comment]
(speaking as an enthusiastic css hater,) z-index is such a stupid hack. upping the value to something larger does seem like the "correct" solution for the issue, an extension's modal dialog should stay on top of the website.

i honestly don't feel like checking out why the right-click option works. not sure when i'll push this, sorry for the intermittent inconvenience.

**Comment by BryanWall** [comment]
I just noticed that the right click option opens both dialogs, the regular one and the right click one. I think it was happening before, but it wasn't as obvious because the regular dialog was hidden behind the other page content. Probably a different issue, but uncovered by fixing this one (I installed your fixed version manually).

<img width="808" alt="Two-Dialogs" src="https://user-images.githubusercontent.com/5903057/156796113-f3e8dc18-bbb2-4a7f-9693-9276c76672e0.png">

**Comment by bogenpirat** [comment]
oh man. i specifically did NOT want to be a UI designer. and i think it's showing.

thanks for reporting this, and thanks for trying out the code! i'm too lazy to fix it now, if it's functionally incapacitating in some way, feel free to open another issue.

**Comment by BryanWall** [comment]
Definitely not "incapacitating"...  it still works, although I think you have to use the smaller dialog which is the right click one. If you right click and use the "regular" dialog, I think it may not work which. It doesn't happen on all sites. I just tried it on another site and the second dialog didn't appear.
