### ISSUE TITLE
Having trouble with the link catching for a site

### ISSUE THREAD

**Issue by wb6vpm** [bogenpirat/remote-torrent-adder#335]
RTA keeps failing to capture the link for the torrent (throws an error) at a specific site, and I'm not sure what I need to put in (I hate expressions!). All links and domain names have been sterilized.

I have put in every variation I can think of to get it to pick it up, but it just won't grab it:

(i?).domain\.com\/download\.php\?id=/\d+
(i?).ssl\.domain\.com\/download\.php\?id=/\d+
(i?)download\.php\?id=/\d+
download\.php\?id=/\d+

The actual link is https://ssl.domain.com/download.php?id=7345504

If I click the link, it downloads the torrent just fine through the browser, but RTA won't capture it.

Any ideas?

![Screenshot 2022-10-28 20 00 48 edited](https://user-images.githubusercontent.com/24217989/198793382-806bbbc9-7171-404c-bc42-04747c393ab8.png)

**Comment by bogenpirat** [comment]
> (I hate expressions!)

it shows.

> The actual link is https://ssl.domain.com/download.php?id=7345504

`domain\.com/download\.php\?id=\d+` should work.

but judging from your screenshot, there are (at least) two separate issues at play here.
1. obviously your regex capturing woes - maybe they'll work with the above filter
2. there's a chance that the `download.php` script doesn't directly deliver the torrent file, but an intermediate page that, in a regular tab, then downloads the torrent file. RTA would in this case send that intermediate page to ruTorrent, which according to your screenshot then complains about its contents. does adding via right-click on a link and then choosing RTA's context menu entry work?
3. there's a chance that the links you're trying to capture are generated asynchronously by a script on the page. in that case, RTA (currently) doesn't have a chance to find them and register click-actions to redirect them. if the right-click route works, this might be the case. you might be able to address this by tuning the "scan delay" setting in RTA's options under the "link catching" tab. try something between 3000 and 5000 (3-5 sec).

**Comment by wb6vpm** [comment]
Issue was resolved with updating regex.
