### ISSUE TITLE
500: Unacceptable file type, only regular file is allowed. (qbittorent)

### ISSUE THREAD

**Issue by 13Dima13** [bogenpirat/remote-torrent-adder#337]
![image](https://user-images.githubusercontent.com/17461617/211224140-de546b50-32b4-4470-bffd-53f6b051d9dc.png)

Chrome Version 108.0.5359.125 (Official Build) (64-bit), default clean installation.
I checked - just removed my credentials from extension and nothing changed, so issue in passing login and password.

```
Failure
Server responded with an irregular HTTP
error code:
500: Unacceptable file type, only regular
file is allowed.
```

```
​POST http://<MY_Qbittorent_IP>:8080/upload.cgi 500 (Internal Server Error)
XMLHttpRequest.sendAsBinary @ functions.js:9
RTA.clients.vuzeSwingAdder @ VuzeSwingUI.js:30
RTA.dispatchTorrent @ functions.js:16
(anonymous) @ functions.js:90
Promise.then (async)
RTA.getTorrent @ functions.js:72
RTA.genericOnClick @ functions.js:201
(anonymous) @ extensions::contextMenusHandlers:86
```

**Comment by bogenpirat** [comment]
> RTA.clients.vuzeSwingAdder @ VuzeSwingUI.js:30
you've set the wrong torrent client. try qbittorrent?

**Comment by 13Dima13** [comment]
Sorry, you are right, it is very not user friendly, I even didn`t notice that there are many types
![image](https://user-images.githubusercontent.com/17461617/211356193-81443f45-29bc-4105-8bc8-231b5c9b40fd.png)
