### ISSUE TITLE
Can no longer log into qBittorrent server

### ISSUE THREAD

**Issue by PhilippeMH** [bogenpirat/remote-torrent-adder#356]
Hi remote adder team,

I am using remote torrent adder on windows Chrome. Since a few months, without changing anything, my remote additions starting to fail with a could not fetch error.  Looking into thee dev console networks tab, it looks like it cannot log in.
![image](https://github.com/user-attachments/assets/62819f2a-d8e9-4349-a945-2c6c45465287)
I tried reinstalling the server and the plugin (settings seem to keep when you do that).

Any advice how to fix or how I can help track it down?
Thanks in advance!

**Comment by bogenpirat** [comment]
connection refused usually means you're trying to connect to a port that is not open. you could check your configuration of qbt with regards to that

**Comment by PhilippeMH** [comment]
I believe my port setup should be OK. I should be able to receive calls from outside. Any other way to verify that? Maybe try to ping my public IP and that port?

The server is configured with number 123 (purple redact in image). Also I turned NAT on - I never had that when it worked, I just tried to see if it would help and it doesn't.
![image](https://github.com/user-attachments/assets/3ac0cf3c-c736-4774-9691-b350739e0c8d)
Below is from my router setup. Black redacted is my internal IP where the web server is hosted. Next are the port translations. Purple is that number 123. Blue is the number I set for the qB client and green is unrelated.
![image](https://github.com/user-attachments/assets/51099812-7e00-4c12-9f70-81e969698d95)
And finally my Chrome extention setup.
![image](https://github.com/user-attachments/assets/e445be8d-7030-42f0-bfc4-76407548047b)
I hope the answer is in here somewehre...

**Comment by bogenpirat** [comment]
from your first screenshot, you seem to have misconfigured your ip address in qbt. it should only contain the ip (i.e. the loopback device's 127.0.0.1, not the port bit ":8080"). right now, qbt is not able to start the webui and it tells you so on that first screenshot.

apart from that - if all you want to do is send torrents to a locally running qbt instance bound to the loopback interface, your config looks fine (so long as your port matches the one set in qbt).

if you want to reach it from the outside, then you'll need to deal with NAT and RTA configuration's port setting would need to be the NATed port, with the IP being the 'outside' IP of your NAT setup.

**Comment by PhilippeMH** [comment]
Thank you - makes sense. I didn't put the :8080 there. Must have been caused by some update.
I fixed it an now, after about 10-15 seconds waiting, I get:
![image](https://github.com/user-attachments/assets/1296ab5e-e934-44a4-999c-826ae9766ea3)

Here let me show you a bigger piece of my qB config - maybe I effed up some more...
![image](https://github.com/user-attachments/assets/13dc0f60-43b4-4186-9d27-eeeeb64e9844)

**Comment by bogenpirat** [comment]
alright, so assuming you've set the port in RTA's config to 64456 as well, the only thing you should have to do in addition is disable SSL. a connection to a loopback device cannot(?) contain a valid certificate covered by any certificate authority, plus if you're just communicating within the same machine, there's not really a need for encrypting the traffic.

**Comment by PhilippeMH** [comment]
Looks like it didn't work, but after I restarted qB, it worked (no SSL).
Super, thank you very much for guiding me to a solution, very much appreciated!

<3
